### ISSUE TITLE
[Feature Request] Neovim/vim support

### ISSUE THREAD

**Issue by jin-ahn** [tim-hub/obsidian-bible-reference#10]
Hi, 

I know that this is a long shot but I was wondering if you could create a  neovim plugin that does the exact samething as this? I use neovim to edit my notes and obsidian to view because obsidian's vim shortcuts are not as robust.

Thank you!

**Comment by tim-hub** [comment]
Thanks for the feedback and suggestion.

It is not impossible, but the only problem is that I do not have experience in Lua/NeoVim Plugin
