### ISSUE TITLE
Create proper 429 request limit error response

### ISSUE THREAD

**Issue by brennenputh** [tim-hub/obsidian-bible-reference#101]
## The Problem
The error is unclear when this plugin hits a request limit.

## Reproduction
Type `--John1:1-3` in the editor, and then type a `0` at the end and delete it repeatedly.  Eventually, the request will return a HTTP 429 status code, indicating it's hitting a rate limit.  This is not shown to the user, however, and simply causes the suggester to stop updating.

## Proposed Solution
Return the error in some way to the user - either by a notification popup or by replacing the content in the suggester with something relevant.

**Comment by tim-hub** [comment]
😢

**Comment by tim-hub** [comment]
a good idea

**Comment by brennenputh** [comment]
As a sidenote and addition - when I was looking for the cause of this, I had to replace the fetch in [this line](https://github.com/tim-hub/obsidian-bible-reference/blob/21b1b5da0cf31c058c0d96807873869f36257acd/src/provider/BibleProvider.ts#L65) with `requestUrl` to get it to spit out a real error instead of a CORS error.  Likely a good change to make, but too small for a PR to fix only that.

**Comment by joelishness** [comment]
Hello,
I think I have been running into this lately, off and on.
I had tried clearing cache, switching devices, uninstall/reinstall, etc.

Finally today I found this in the Obsidian Console:
```
plugin:obsidian-bible-reference:30  GET https://bolls.life/get-text/NASB/46/13/ 429 (Too Many Requests)
query @ plugin:obsidian-bible-reference:30
eval @ plugin:obsidian-bible-reference:56
getVerses @ plugin:obsidian-bible-reference:56
fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
U @ plugin:obsidian-bible-reference:56
getSuggestions @ plugin:obsidian-bible-reference:56
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
c @ app.js:1
u @ app.js:1
setTimeout
h @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
xr @ app.js:1
Sr @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
plugin:obsidian-bible-reference:30 error while querying SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
query @ plugin:obsidian-bible-reference:30
await in query
eval @ plugin:obsidian-bible-reference:56
getVerses @ plugin:obsidian-bible-reference:56
fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
U @ plugin:obsidian-bible-reference:56
getSuggestions @ plugin:obsidian-bible-reference:56
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
c @ app.js:1
u @ app.js:1
setTimeout
h @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
xr @ app.js:1
Sr @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
plugin:obsidian-bible-reference:56 Invalid Bible reference: Error: Invalid verse number: "" is not a number
    at J (plugin:obsidian-bible-reference:54:14314)
    at eval (plugin:obsidian-bible-reference:54:17224)
    at Array.forEach (<anonymous>)
    at I (plugin:obsidian-bible-reference:54:14672)
    at U (plugin:obsidian-bible-reference:56:3385)
    at ve.getSuggestions (plugin:obsidian-bible-reference:56:4620)
    at t.trigger (app.js:1:1642427)
    at e.trigger (app.js:1:2620219)
    at app.js:1:2413638
    at c (app.js:1:552123)
U @ plugin:obsidian-bible-reference:56
getSuggestions @ plugin:obsidian-bible-reference:56
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
c @ app.js:1
u @ app.js:1
setTimeout
h @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
xr @ app.js:1
Sr @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
plugin:obsidian-bible-reference:30  GET https://bolls.life/get-text/NASB/46/13/ 429 (Too Many Requests)
query @ plugin:obsidian-bible-reference:30
eval @ plugin:obsidian-bible-reference:56
getVerses @ plugin:obsidian-bible-reference:56
fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
U @ plugin:obsidian-bible-reference:56
getSuggestions @ plugin:obsidian-bible-reference:56
t.trigger @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
c @ app.js:1
u @ app.js:1
setTimeout
h @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
xr @ app.js:1
Sr @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
plugin:obsidian-bible-reference:30 error while querying SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
```

Which lead me to this issue.
Is it accurate that this issue was never resolved?

**Comment by tim-hub** [comment]
> Hello,
> I think I have been running into this lately, off and on.
> I had tried clearing cache, switching devices, uninstall/reinstall, etc.
> 
> Finally today I found this in the Obsidian Console:
> ```
> plugin:obsidian-bible-reference:30  GET https://bolls.life/get-text/NASB/46/13/ 429 (Too Many Requests)
> query @ plugin:obsidian-bible-reference:30
> eval @ plugin:obsidian-bible-reference:56
> getVerses @ plugin:obsidian-bible-reference:56
> fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
> U @ plugin:obsidian-bible-reference:56
> getSuggestions @ plugin:obsidian-bible-reference:56
> t.trigger @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> c @ app.js:1
> u @ app.js:1
> setTimeout
> h @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> xr @ app.js:1
> Sr @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> plugin:obsidian-bible-reference:30 error while querying SyntaxError: Unexpected token '<', "<html>
> <h"... is not valid JSON
> query @ plugin:obsidian-bible-reference:30
> await in query
> eval @ plugin:obsidian-bible-reference:56
> getVerses @ plugin:obsidian-bible-reference:56
> fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
> U @ plugin:obsidian-bible-reference:56
> getSuggestions @ plugin:obsidian-bible-reference:56
> t.trigger @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> c @ app.js:1
> u @ app.js:1
> setTimeout
> h @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> xr @ app.js:1
> Sr @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> plugin:obsidian-bible-reference:56 Invalid Bible reference: Error: Invalid verse number: "" is not a number
>     at J (plugin:obsidian-bible-reference:54:14314)
>     at eval (plugin:obsidian-bible-reference:54:17224)
>     at Array.forEach (<anonymous>)
>     at I (plugin:obsidian-bible-reference:54:14672)
>     at U (plugin:obsidian-bible-reference:56:3385)
>     at ve.getSuggestions (plugin:obsidian-bible-reference:56:4620)
>     at t.trigger (app.js:1:1642427)
>     at e.trigger (app.js:1:2620219)
>     at app.js:1:2413638
>     at c (app.js:1:552123)
> U @ plugin:obsidian-bible-reference:56
> getSuggestions @ plugin:obsidian-bible-reference:56
> t.trigger @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> c @ app.js:1
> u @ app.js:1
> setTimeout
> h @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> xr @ app.js:1
> Sr @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> plugin:obsidian-bible-reference:30  GET https://bolls.life/get-text/NASB/46/13/ 429 (Too Many Requests)
> query @ plugin:obsidian-bible-reference:30
> eval @ plugin:obsidian-bible-reference:56
> getVerses @ plugin:obsidian-bible-reference:56
> fetchAndSetVersesText @ plugin:obsidian-bible-reference:56
> U @ plugin:obsidian-bible-reference:56
> getSuggestions @ plugin:obsidian-bible-reference:56
> t.trigger @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> c @ app.js:1
> u @ app.js:1
> setTimeout
> h @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> xr @ app.js:1
> Sr @ app.js:1
> (anonymous) @ app.js:1
> (anonymous) @ app.js:1
> plugin:obsidian-bible-reference:30 error while querying SyntaxError: Unexpected token '<', "<html>
> <h"... is not valid JSON
> ```
> 
> Which lead me to this issue.
> Is it accurate that this issue was never resolved?

This is server side issues which cannot be resolved by client side. However can you check latest version, it support offline using bbe as a source.

**Comment by joelishness** [comment]
> This is server side issues which cannot be resolved by client side.

Yes, understood. I thought the request in this issue was for the client to make the issue more apparent for the user, rather than an ambiguous error.

> However can you check latest version, it support offline using bbe as a source.

Which version was this changed for, please?
I have been keeping up to date, most recently on Version 26.06.07 when I encountered this issue last night.
Interestingly, this morning the error still occurs for the same verse (1 Cor 13:6). This seems to contradict rate-limiting as the cause, I would have thought it should have refreshed by now. Instead it seems to suggest that some local cache is being queried but is corrupted.

Just now I upgraded to 26.07.15-1
And then 1 Cor 13:6 was successful! 🎉

So that's great news, but I don't understand the mechanism(s) at play.
If it was rate limiting, why did it still persist the next day?
If it was local cache, why did the new version (which queries the local cache? Did I understand correctly?) suddenly start working?

If it makes sense to you, I would be grateful if you would please help me understand, too.

Thanks again!

**Comment by tim-hub** [comment]
> > This is server side issues which cannot be resolved by client side.
> 
> Yes, understood. I thought the request in this issue was for the client to make the issue more apparent for the user, rather than an ambiguous error.
> 
> > However can you check latest version, it support offline using bbe as a source.
> 
> Which version was this changed for, please? I have been keeping up to date, most recently on Version 26.06.07 when I encountered this issue last night. Interestingly, this morning the error still occurs for the same verse (1 Cor 13:6). This seems to contradict rate-limiting as the cause, I would have thought it should have refreshed by now. Instead it seems to suggest that some local cache is being queried but is corrupted.
> 
> Just now I upgraded to 26.07.15-1 And then 1 Cor 13:6 was successful! 🎉
> 
> So that's great news, but I don't understand the mechanism(s) at play. If it was rate limiting, why did it still persist the next day? If it was local cache, why did the new version (which queries the local cache? Did I understand correctly?) suddenly start working?
> 
> If it makes sense to you, I would be grateful if you would please help me understand, too.
> 
> Thanks again!

The API is a a third party API, bolls life, which the rate limit period may not be daily based, I don't think they clearly explain the rate limit either. 


Local cache:
This is new thing, every time you fetch a verse it will cache locally, if you haven't fetched before, it need to fetch it.

Offline Mode:
- BBE Translation is built into this plugin, so when their is not network or enable offline mode, BBE will be used.
