### ISSUE TITLE
make book name translateable

### ISSUE THREAD

**Issue by hi-reeve** [tim-hub/obsidian-bible-reference#104]
**Is your feature request related to a problem? Please describe.**
currenlty you can only find a verse by it's english book name. will be very good if we can make it more generic based on available translateable? so people can contribute the book name on their own languages?

**Comment by benjayahari** [comment]
I'm looking into this 👀

**Comment by tim-hub** [comment]
> **Is your feature request related to a problem? Please describe.**
> currenlty you can only find a verse by it's english book name. will be very good if we can make it more generic based on available translateable? so people can contribute the book name on their own languages?
> 

I like this idea too.

**Comment by tim-hub** [comment]
> I'm looking into this 👀 

I am thinking, 

Probably we can go with a multiple languages dictionary locally to match book names, 

Or use a search/query on top of the bible API.

Both require some a big chunk of time.

**Comment by hi-reeve** [comment]
> > I'm looking into this 👀
> 
> I am thinking,
> 
> Probably we can go with a multiple languages dictionary locally to match book names,
> 
> Or use a search/query on top of the bible API.
> 
> Both require some a big chunk of time.

well good idea, i've been requesting the search by book name api to the bolls api author. 
let's see how is it when he's releasing it.

**Comment by hi-reeve** [comment]
search by book name is now available on bolls api @tim-hub

**Comment by tim-hub** [comment]
> search by book name is now available on bolls api @tim-hub

Can you give me an example of the usage of naming seaching on bolls api?

**Comment by hi-reeve** [comment]
> > search by book name is now available on bolls api @tim-hub
> 
> Can you give me an example of the usage of naming seaching on bolls api?

sorry i have miss communication with the author.
anyway, the author said he won't make the api. we can do it in the clientside, so from the current selected bible version, get the list of the book and just find it using string function

**Comment by tim-hub** [comment]
> > > search by book name is now available on bolls api @tim-hub
> > 
> > 
> > Can you give me an example of the usage of naming seaching on bolls api?
> 
> sorry i have miss communication with the author. anyway, the author said he won't make the api. we can do it in the clientside, so from the current selected bible version, get the list of the book and just find it using string function

it will work but maybe slow, 

This is a big chunk of work to support it, need a proper accurate mapping of different language book names.

**Comment by oscampo** [comment]
My solution (for book names on spanish), was edit directly the main.js file on the definition of module2.exports definition appending the book names in spanish. 
Here a fragment:

```
module2.exports = [
      {
        names: "Génesis Genesis Ge Gen".split(" "),
        verses: [31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 20, 18, 24, 21, 16, 27, 33, 38, 18, 34, 24, 20, 67, 34, 35, 46, 22, 35, 43, 55, 32, 20, 31, 29, 43, 36, 30, 23, 23, 57, 38, 34, 34, 28, 34, 31, 22, 33, 26]
      },

      {
        names: "Éxodo Exodo Exodus Ex Exo".split(" "),
        verses: [22, 25, 22, 31, 23, 30, 25, 32, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27, 25, 26, 36, 31, 33, 18, 40, 37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38, 29, 31, 43, 38]
      },
```

etc...
Additionaly, I extracted that portion of code and save as a simple txt file that I use to insert again the names each time obsidian-bible-reference plugin is updated.

**Comment by tim-hub** [comment]
> My solution (for book names on spanish), was edit directly the main.js file on the definition of module2.exports definition appending the book names in spanish. 
> Here a fragment:
> 
> ```
> module2.exports = [
>       {
>         names: "Génesis Genesis Ge Gen".split(" "),
>         verses: [31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 20, 18, 24, 21, 16, 27, 33, 38, 18, 34, 24, 20, 67, 34, 35, 46, 22, 35, 43, 55, 32, 20, 31, 29, 43, 36, 30, 23, 23, 57, 38, 34, 34, 28, 34, 31, 22, 33, 26]
>       },
> 
>       {
>         names: "Éxodo Exodo Exodus Ex Exo".split(" "),
>         verses: [22, 25, 22, 31, 23, 30, 25, 32, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27, 25, 26, 36, 31, 33, 18, 40, 37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38, 29, 31, 43, 38]
>       },
> ```
> 
> etc...
> Additionaly, I extracted that portion of code and save as a simple txt file that I use to insert again the names each time obsidian-bible-reference plugin is updated.
> 
>  

Do you mind sharing the translation text?

I saw a source for Poland translation, I believe I can update to support both Poland and Spain translation.

**Comment by oscampo** [comment]
Shure

> Do you mind sharing the translation text?

sure...
Please download form here: https://oscampo.github.io/sharing/BibleBookNames.txt
