### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by obxjack** [tim-hub/obsidian-bible-reference#105]
**Describe the bug**
The plugin doesn’t appear to work on the iPad. 
I type —John1:1 and nothing happens.

**To Reproduce**
1. Open new file
2. Type —1John1:1

**Expected behavior**
Expect verse suggestion to appear.

**What Device Do You Use(please complete the following information):**
 - Device: iPad Pro
 - OS: iPadOS
 - Version 16.5.1

**Comment by tim-hub** [comment]
Hi @obxjack 

FYI, I tried on my own old iPad, it worked as expected. 

Please understand that the iPad is the hardest to debug for Obsidian plugins. 

It could be due to network, API endpoint, etc

Do you have any update now?


Ref:
https://forum.obsidian.md/t/access-the-obsidian-console-on-ios-app/23476

**Comment by leesyang** [comment]
I have the same issue on my iPad Pro, 16.6. No verse suggestion appears.

**Comment by tim-hub** [comment]
@obxjack @leesyang 

Did you use the version from bible.com or bolls life?

https://github.com/tim-hub/obsidian-bible-reference/issues/117

**Comment by tim-hub** [comment]
> @tim-hub does not work with v1.9.0. Using ESV bolls life.

Thanks, @leesyang 

Do you mean it work when using ESV under app version 1.9.0?

Or does not work under version 1.9.0 at all?

**Comment by leesyang** [comment]
> > @tim-hub does not work with v1.9.0. Using ESV bolls life.
> 
> Thanks, @leesyang
> 
> Do you mean it work when using ESV under app version 1.9.0?
> 
> Or does not work under version 1.9.0 at all?

I'm using version 1.9.0 with the Bolls Life ESV and it is not working.

**Comment by NeonSupernova** [comment]
I believe I have found the issue. It would seem that on iOS, or iPadOS, using - twice in a row, automatically formats it to —, this can be resolved by using an alternate keyboard that does not adjust this --.

**Comment by tim-hub** [comment]
> I believe I have found the issue. It would seem that on iOS, or iPadOS, using - twice in a row, automatically formats it to —, this can be resolved by using an alternate keyboard that does not adjust this --.

Thanks.

I updated the wiki of how to turn off smart punctuation and Readme to resolve this temporarily. I believe this smart punctuation conflict is not only with this plugins, but also some other iOS apps too.


- https://github.com/tim-hub/obsidian-bible-reference/commit/3c7df5287aa75e5a48a55a024a6b9b6d5f7e77cd
- [How to use](https://github.com/tim-hub/obsidian-bible-reference/wiki/How-to-use)
