### ISSUE TITLE
Option to remove all line breaks when choosing paragraph formatting

### ISSUE THREAD

**Issue by JenFau** [tim-hub/obsidian-bible-reference#106]
When paragraph formatting is selected, it would be really good to prevent additional line breaks from being added so that everything is indeed on one paragraph. 

This would prevent me having to search and replace line breaks with spaces.

**Comment by tim-hub** [comment]
Hi @JenFau Would you mind taking a screenshot of it?

**Comment by JenFau** [comment]
Hi @tim-hub, I hope this helps? 

<img width="862" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/13613183/d8ae1930-1565-4172-86db-d5f71680b9e1">

<img width="786" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/13613183/d11d1f82-7975-4e27-9ba7-deeb40bb4e31">

<img width="650" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/13613183/fada5836-35cf-42e1-868f-a0e4d103f86c">

<img width="657" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/13613183/f32e680e-ac59-445d-8713-b852cb957851">

**Comment by JenFau** [comment]
Oh, sorry - and this is what I'd like an option to achieve - all in one paragraph with no breaks: 

<img width="670" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/13613183/6a0327a7-129d-4b18-ad6f-63de835588bd">

**Comment by tim-hub** [comment]
> Oh, sorry - and this is what I'd like an option to achieve - all in one paragraph with no breaks:
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/13613183/259176795-6a0327a7-129d-4b18-ad6f-63de835588bd.png">

I know what you mean now.

Thanks,

I need more research, 

some versions from the API returns the verses with new line I believe, it may be tricky to not respect the format. 

But anyway this need me to do more research.

**Comment by Kilarin** [comment]
I would like to second this request.  An option to turn off </br> line breaks would be very helpful to me.
