### ISSUE TITLE
Conflict with icon shortcodes

### ISSUE THREAD

**Issue by OfficerHalf** [tim-hub/obsidian-bible-reference#11]
Because both your plugin and [icon shortcodes](https://github.com/aidenlx/obsidian-icon-shortcodes) are waiting on a `:` character (I think that's the conflict anyway), I can't get this to work with both enabled at the same time. Would be excellent to be able to insert a verse/passage using a command from the palette.

**Comment by tim-hub** [comment]
Thanks, that is a good idea, actually
