### ISSUE TITLE
[Feature] Option to disable `[!Bible]-` prefix

### ISSUE THREAD

**Issue by TrebledJ** [tim-hub/obsidian-bible-reference#110]
First of all, thanks for the plugin. Works nicely so far.

The `[!Bible]` icon prefix is not standard Markdown syntax, so when copy-pasting Obsidian onto another Markdown renderer, it may simply render as an ugly `[!Bible]` instead of the icon.

It'd be convenient to have an option to disable this icon so that the Bible verse renders as a simple blockquote.

Thanks~

**Comment by tim-hub** [comment]
Thanks for your 2 issue request, they are very good points. :)

**Comment by tim-hub** [comment]
This should be fixed after release of [2.4.0](https://antioch.tech/obsidain-bible-reference-plugin-2-4-0-changelog/)


Please let me know if you still get an issue.
