### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by fcom000** [tim-hub/obsidian-bible-reference#117]
the plugin simply does not work, it is active so I can run the command "Bible reference: verse lookup", but when I write inside the verse there is always no answer, nothing. Also if I write --John1:1 etc I never had any output. Tried also without firewall no difference.

Is there some extra plugin I need to run it? 

I tried it also in android phone, same problem, nothing happens...

**Comment by tim-hub** [comment]
If on windows, can I try open developer console to see 
what logs is there?

**Comment by tim-hub** [comment]
this is the toggle for enable the developer console.

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/81094c06-4344-47c0-8a5c-ebe7a9df18b9)


If you can get some logs, that will be very helpful. I am very curious why this could happen as well.

**Comment by SlothUS** [comment]
Also getting the same issue. Here's what my console produces - 


![](https://i.imgur.com/9ywDvBP.png)

**Comment by tim-hub** [comment]
> Also getting the same issue. Here's what my console produces -
> 
> ![](https://camo.githubusercontent.com/ecd229274ba02d590aa968cba8c1da021d8ca083639f7ce041cd054e877eb657/68747470733a2f2f692e696d6775722e636f6d2f397977447642502e706e67)

Hi @SlothUS 

Thanks for this.

**Comment by tim-hub** [comment]
@fcom000 @SlothUS 

Can you try to switch the Bible Version provider by Bolls life? in the settings.

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/c5933f89-9dd9-42b2-957f-fd9c4cf58b5e)


This is a CORS issue, which is a server side issue, I know this will happen one day, just don't know it happens so fast. 

CORS issue, which it blocks the 3rd part API consume to consume its API. 

This is why it failed. 

To fix this, need to host a server by my self.

For now I will suggest you to use bolls life versions.

**Comment by tim-hub** [comment]
this should be fixed in 1.9.0 by switching the default version, please re-open this if not.

**Comment by fcom000** [comment]
thanks very much, it works with the Bolls life. I was wondering if it is easy to host a Bible Api offline in my computer so even without internet the plugin works (and there will be no update issues?
