### ISSUE TITLE
ESV API Support

### ISSUE THREAD

**Issue by OfficerHalf** [tim-hub/obsidian-bible-reference#12]
If you aren't interested in taking this on, I might. There's an [official English Standard Version API](https://api.esv.org/docs/). Though not my 100% preferred translation, it's a reasonable one that I do sometimes read. It would require some setup to use, with the end user providing an API key.

It has lots of options, none of which conform to the open-bibles API. 😆 So it would be an entirely separate implementation.

**Comment by tim-hub** [comment]
I was thinking to build a simple rest api relay to do this, but haven't gotten enough time to design and make it, 😢

**Comment by billpetro** [comment]
I am very interested in the ESV version. I'm not a programmer but would be willing to help in other ways to see this implemented.

**Comment by tim-hub** [comment]
ESV was added in 1.0.2
