### ISSUE TITLE
Bible book and Chapter linking gone?

### ISSUE THREAD

**Issue by cjulin6651** [tim-hub/obsidian-bible-reference#128]
**Describe the bug**
As of yesterday evening, I no longer have the ability to auto link the book of the Bible or chapter. Is this a glitch or was the feature removed? I loved this feature. 

**To Reproduce**
1. Go to the plugin settings and scroll to "Tagging and Linking Settings

**Expected behavior**
You'll not see the option to link any longer.

**Screenshots**
![IMG_1179](https://github.com/tim-hub/obsidian-bible-reference/assets/38538687/8bdd6a70-efcd-445b-96a9-b063da0a0c4c)
![bibleref scrn shot 1](https://github.com/tim-hub/obsidian-bible-reference/assets/38538687/93786cf6-b23d-4157-ac6c-9a3abb238613)

**What Device Do You Use(please complete the following information):**
 - Device: iPhone 12mini and Macbook

**Comment by tim-hub** [comment]
Thanks for your feedback.

It was removed in this pr, and there are 2 reasons there, one is the UI, the other is the link formation. 
https://github.com/tim-hub/obsidian-bible-reference/pull/119#issuecomment-1705014684

There are more discussion here,

https://github.com/tim-hub/obsidian-bible-reference/discussions/115
https://github.com/tim-hub/obsidian-bible-reference/discussions/127

Anyway, will think about it and try to resolve the limitations to get it back. 

If you got some ideas, please feel free to join the discussion. 😁

**Comment by tim-hub** [comment]
this should be resolved in release https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.3.0

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/70fee0d0-5b8a-4a22-8ea8-4f0b09693afd)
