### ISSUE TITLE
Show internationalized book name

### ISSUE THREAD

**Issue by kailichiang** [tim-hub/obsidian-bible-reference#134]
**Is your feature request related to a problem? Please describe.**
When I set the default bible version to non-English version, I'd like to see the correspoding book name.
For example, I set it as "Chinese - Chinese Union Version (Traditional) @Bolls Life," When I type `--genesis 2:3`, instead of showing `Genesis 2:3 - CUV`, I'd like to see it as `創世紀 2:3 - CUV` or `創 2-3` (this is the short name of Genesis in Chinese).

**Describe the solution you'd like**
Instead of showing English book name, show book name in corresponding language.

**Describe alternatives you've considered**
Not yet know. Probably one more option to set language?

**Additional context**
<img width="745" alt="Xnip2023-09-13_14-55-19" src="https://github.com/tim-hub/obsidian-bible-reference/assets/6218405/5c696b2c-172f-4a48-8844-df9f40164d97">

**Comment by kailichiang** [comment]
Sure. Plz forward me it.

**Comment by tim-hub** [comment]
Currently the trigger of book names could be done in more langauges in 2.1.1

For example, this Italian version
![](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/5c04e4b9-531c-4dac-973e-632dc3e74385)

**Comment by tim-hub** [comment]
> Sure. Plz forward me it.

Hi @kailichiang 



This is the repo to have different translations, 

ref: https://github.com/AntiochTechnology/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations

It is a JSON file in a spercific structure, there are 3 langauges there, if you can help for Chinese, that will be great

feel free to ping me if need help

**Comment by tim-hub** [comment]
In version 2.2.0

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.2.0

Multiple languages are supported, Spanish, Italian, Japanese.

**Comment by grnsmn** [comment]
Hi @tim-hub , I'm interested in helping to add translation support for the reference header and solve this issue. However, after inspecting the code, I still can't figure out how this is generated.

While I see that the plugin fetches translation references from the library at the following link: https://github.com/AntiochTechnology/bible-reference-toolkit/tree/master/packages/bible-book-names-intl, I'm still unclear on how it doesn't seem to translate the header into the user's chosen language.

Could you provide more information or guidance on how the translation for the reference header can be implemented? This would help me better understand how to contribute effectively.

Thank you!

**Comment by tim-hub** [comment]
> Hi @tim-hub , I'm interested in helping to add translation support for the reference header and solve this issue. However, after inspecting the code, I still can't figure out how this is generated.
> 
> While I see that the plugin fetches translation references from the library at the following link: https://github.com/AntiochTechnology/bible-reference-toolkit/tree/master/packages/bible-book-names-intl, I'm still unclear on how it doesn't seem to translate the header into the user's chosen language.
> 
> Could you provide more information or guidance on how the translation for the reference header can be implemented? This would help me better understand how to contribute effectively.
> 
> Thank you!

Uh, currently, the package was used only for match the book name.

If want to show it in header (rendering), here need to be changed. https://github.com/tim-hub/obsidian-bible-reference/blob/0ac39dd6d50129d73d00e9583d96c1859de7a4d0/src/provider/BaseBibleAPIProvider.ts#L47C1-L54C4

to use the package `bible-book-names-intl`

But careful, since it is a base class.
