### ISSUE TITLE
Please add Spanish Book Names

### ISSUE THREAD

**Issue by oscampo** [tim-hub/obsidian-bible-reference#138]
Thanks in advance!!

**Comment by tim-hub** [comment]
Hi @oscampo 

Would you mind helping add the Spanish translation book names?


This is the repo to have different translations,

ref: https://github.com/AntiochTechnology/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations

It is a JSON file in a spercific structure, there are 3 langauges there, if you can help for Spanish, that will be great

feel free to ping me if need help

**Comment by tim-hub** [comment]
this is duplicated of https://github.com/tim-hub/obsidian-bible-reference/issues/134

**Comment by oscampo** [comment]
> Hi @oscampo
> 
> Would you mind helping add the Spanish translation book names?
> 
> This is the repo to have different translations,
> 
> ref: https://github.com/AntiochTechnology/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations
> 
> It is a JSON file in a spercific structure, there are 3 langauges there, if you can help for Spanish, that will be great
> 
> feel free to ping me if need help
Great! I just created the file "sp.json" following the format you suggest. Here is the file:
[spanishBookNames.zip](https://github.com/tim-hub/obsidian-bible-reference/files/12615139/spanishBookNames.zip)

**Comment by oscampo** [comment]
Hi, 
Any problem with the json file ? I saw some reports of errors in the build, but they are related to my file?... sorry I'm checking the report but I can't find which are the errors on my file, because I only see some errors related to another file with book names in english

**Comment by tim-hub** [comment]
> Hi, 
> Any problem with the json file ? I saw some reports of errors in the build, but they are related to my file?... sorry I'm checking the report but I can't find which are the errors on my file, because I only see some errors related to another file with book names in english

I think there are some small things need to update.

I think I need to update the markdown file to make it clear.

The tests will check the files structure and whether there are duplication.

- For example, short names can be empty array but not be the same as the full name.

- Books short names have to be unique to each other.

Will check tomorrow and update the readme and let you know the reason

**Comment by oscampo** [comment]
Ok... I understand... maybe there is a problem with the name "Job" because is the same for the name of the book end for the short name

**Comment by oscampo** [comment]
@tim-hub I check the json file and updated with unique or blank shortnames

**Comment by tim-hub** [comment]
> @tim-hub I check the json file and updated with unique or blank shortnames

Thanks

**Comment by oscampo** [comment]
Hi @tim-hub I check you merged sp.json last week, but the obsidian plugin is not updated. Any idea when the version with spanish book names will be available?

**Comment by tim-hub** [comment]
Sorry for that, the lib need to be updated to use the Spanish translation

**Comment by tim-hub** [comment]
Working on it

**Comment by tim-hub** [comment]
@oscampo 

This should be fixed in version 2.2.0, Thanks for the patience.

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.2.0
