### ISSUE TITLE
Unable to look up numbered books

### ISSUE THREAD

**Issue by chrisg32** [tim-hub/obsidian-bible-reference#139]
**Describe the bug**
I am unable to resolve any numbered books (1 Peter, 2 Corinthians, etc). I have tried from the notes and the lookup dialog, with and without spaces,  and with several variations from [src/data/abbreviations.ts](https://github.com/tim-hub/obsidian-bible-reference/blob/b1882a7a33afa6aff183f9e39287fe6fbcb3f1b9/src/data/abbreviations.ts#L189).

**To Reproduce**
1. Inside a note type ` --1Peter2:20`
2. The verse will be resolved.

1. From the verse lookup dialog type `2Cor1:3-4`
2. The verse will not be resolved.

**Expected behavior**
Numbered books should be able to be resolved.

**Screenshots**

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/1832474/1f3abed6-93f8-4687-9028-30bca9bacaa7)

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/1832474/11c6e7c9-d4ec-47f4-b150-9a605d8d9b00)

**What Device Do You Use(please complete the following information):**
 - Device: Mac
 - OS: Ventura 13.5.2
 - Obsidian Version 1.4.13 (Installer v1.4.13)
 - Version 2.1.2

**Additional context**
Bolls life ESV translation.

**Comment by tim-hub** [comment]
This one seems like related to this one. https://github.com/tim-hub/obsidian-bible-reference/issues/66

**Comment by nRICHd** [comment]
This problem still exists, irrespective of the english translation used - I have the latest version of Obsidian (1.4.14) running on Mac OS, with plug-in version (2.1.4).

Thanks.

**Comment by tim-hub** [comment]
> This problem still exists, irrespective of the english translation used - I have the latest version of Obsidian (1.4.14) running on Mac OS, with plug-in version (2.1.4).
> 
> Thanks.

In progress

**Comment by tim-hub** [comment]
Sorry for the delay,

Recently was quite busy, will try bring it this weekend.

**Comment by tim-hub** [comment]
This should be fixed in version 2.2.0, Thanks for the patience.

**Comment by nRICHd** [comment]
Thanks Tim.

All good from my side.
