### ISSUE TITLE
Bible icon missing

### ISSUE THREAD

**Issue by chrisg32** [tim-hub/obsidian-bible-reference#141]
**Describe the bug**
Bible icon seems to have disappeared with the latest version.

**To Reproduce**
1. Insert a verse
2. Enter reading mode
3. Bible icon is missing

**Expected behavior**
Bible icon displays as before with `[!Bible]`.

**Screenshots**
Not working (Mac Version 2.1.2)
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/1832474/a0e7608f-6f9f-4c33-b1c9-ac80bb4f8efa)

Example of it working (iOS app Version 1.8.4, Obsidian v1.4.8)
![C4FEBD97-215F-446B-8A4D-4574FE5045F6_1_201_a](https://github.com/tim-hub/obsidian-bible-reference/assets/1832474/ea18df3f-3a00-48a6-a20f-54296fd193af)

**What Device Do You Use(please complete the following information):**
 - Device: Mac
 - OS: Ventura 13.5.2
 - Obsidian Version 1.4.13 (Installer v1.4.13)
 - Version 2.1.2

**Additional context**
Bolls life ESV translation.

**Comment by tim-hub** [comment]
this is interesting, it seems like related to the recent obsidian release. 

need to do more investigation

**Comment by tim-hub** [comment]
Will raise this to Obsidian, it seems like custom SVG call our icon is broken now in Obsidian.

**Comment by tim-hub** [comment]
> Will raise this to Obsidian, it seems like custom SVG call our icon is broken now in Obsidian.

https://github.com/obsidianmd/obsidian-api/issues/132

**Comment by tim-hub** [comment]
this should be fixed now in 2.1.4 :)
