### ISSUE TITLE
I added German, Hebrew and Greek

### ISSUE THREAD

**Issue by OfirSinn** [tim-hub/obsidian-bible-reference#142]
I was looking for  initially just for German, my mother tongue, but as soon as I found out how to add translations I added more of my frequently used languages.
The translations are NASB, ELB, LUT, WEC, DHNT, TR, NTGT, LXX

What version is it?
it's 2.1.4

Do you know, is there a public bible API for it?
bolls life

 - I have made a PDF of how I did it, and how you can do it too (as long as the translation you're looking for is in bolls life).

[Bible reference Mod.pdf](https://github.com/tim-hub/obsidian-bible-reference/files/12708018/Bible.reference.Mod.pdf)

Notice that the names of the books when using the plugin are all still in english

**Comment by tim-hub** [comment]
Oh, would you mind adding them here?

So we could simply include it in next release.

https://github.com/tim-hub/obsidian-bible-reference/blob/master/src/data/BibleVersionCollection.ts

**Comment by OfirSinn** [comment]
Yeah of course, added them there, you should be able to view the fork

**Comment by tim-hub** [comment]
see 2.2.1 https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.2.1
