### ISSUE TITLE
Multi-chapter references not possible

### ISSUE THREAD

**Issue by 0majortoms** [tim-hub/obsidian-bible-reference#145]
**Describe the bug**
Can't make a reference that spans multiple chapters.

**To Reproduce**
1. Open any note
2. Type a reference that spans more than one chapter, ex. "--John 1:1-2:2"
3. Plugin recommends a reference that interprets that example as simply "John 1:1-2"
_(This behavior is the same in the Verse Lookup dialog box)_

**Expected behavior**
Should recommend the multi-chapter reference.

**Screenshots**
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/141202013/754b98fa-296d-4374-be0b-30bf9df845de)

**What Device Do You Use:**
 - Device: MacBook Pro 2019
 - OS: macOS Ventura (13.5)
 - Version 1.4.14

**Additional context**
I'm new to the plugin, so it's possible I've missed that this isn't a feature. If so, then I guess this is a feature request.

**Comment by tim-hub** [comment]
This is probably a limitation for the current APP backend design, this need more thorough think to have an efficient multiple chapter support
