### ISSUE TITLE
Spanish short "two letter" names not working (version 2.3.4)

### ISSUE THREAD

**Issue by oscampo** [tim-hub/obsidian-bible-reference#149]
Short "2 letter" names as  "Gn", "Ex", "Lv", "Nm"...... "Mt", "Mr", "Lc" , "Jn".... and  short names as: "1Cor", "2Cor" 
not work in version 2.3.4

Device:	DESKTOP
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor
OS: 	Windows 11 Home Single Language
Version	22H2
Installed on	‎20/‎10/‎2022
OS build	22621.2428
Experience	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by tim-hub** [comment]
Hi @oscampo 

I can reproduce this issue too, checking it now

**Comment by oscampo** [comment]
Hi Tim, 
The problem is that the code of sp.json was not updated with the last one I commited wich contains the correct short names
Here is the right one:
[sp.json](https://github.com/tim-hub/obsidian-bible-reference/files/13033817/sp.json)

**Comment by tim-hub** [comment]
issues are from here. 

the regex trigger requires 3 letters at least. 


https://github.com/tim-hub/obsidian-bible-reference/blob/a2a2cf50ef2f4d3aef6d91b5ca9aa05a3c4d5d26/src/utils/regs.ts#L16

**Comment by tim-hub** [comment]
this release should gets the fix, feel free to let me know if you still get the same issue.

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.3.6

**Comment by oscampo** [comment]
Thanks @tim-hub  I just installed this release and I will check it
