### ISSUE TITLE
Reference to locally stored Bible rather than online

### ISSUE THREAD

**Issue by Sanketikaran** [tim-hub/obsidian-bible-reference#150]
I have a Bible stored in my vault, and would like to be able to refer to that locally stored Bible rather than an online one, so when I am not online, I still have access and I can also annotate my notes on my locally stored Bible.

I would personally find this very beneficial, as it would mean access when not connected online all the time, and being able to edit my Bible as well is really useful.

**Comment by tim-hub** [comment]
Duplicated to https://github.com/users/tim-hub/projects/2/views/1?filterQuery=ca&pane=issue&itemId=18315876

**Comment by BravishkaSkytano** [comment]
That's what [this plugin](https://github.com/kuchejak/obsidian-bible-linker-plugin) is for.

**Comment by tim-hub** [comment]
> That's what [this plugin](https://github.com/kuchejak/obsidian-bible-linker-plugin) is for.

I think linker plugin does not meet this 

`and would like to be able to refer to that locally stored Bible` 

From what I know, linker plugin will create reference as a file for user, but it will not fill the verse for you (aka storing for you).

**Comment by BravishkaSkytano** [comment]
> From what I know, linker plugin will create reference (Link) as a file for user, but it will not fill the verse for you (aka storing for users).

If you have a local version of the Bible saved in your vault, the linker plugin will copy the verse(s) into the page you are on. That's how the plugin works, you can either reference to the verse(s) or copy it onto the page.
