### ISSUE TITLE
Biblebook Tags for numbered Books not working

### ISSUE THREAD

**Issue by fre98fi** [tim-hub/obsidian-bible-reference#153]
**Describe the bug**
When a numbered book like "2 Corinthians" is referenced and a Book-Tag is generated, the generated Tag looks like "#2 Corinthians". The problem here is that Obsidian will not recognize this as a Tag. It should look like "#2Corinthians".

**To Reproduce**
1. Activate Book Tags in the Expert Settings
2. Reference a numbered Book
3. Look for the used Tags

**Expected behavior**
Tags should be in the right format to be recognized by Obsidian

**What Device Do You Use(please complete the following information):**
 - Device: MacBook Pro 14 M1 Pro 2021
 - OS: Sonoma 14.0
 - Obsidian Version 1.4.16
 - Version 2.3.4

**Comment by tim-hub** [comment]
Thanks for raising this, I didn't notice it. Will have a look

**Comment by yintzgit** [comment]
Hi, similar issue in windows11pro: with numbered books (eg Cor, Thess) it is not possible to get the bible text, same with or without tag. Doesnot work in german bible texts (eg Luther, Menge). English works, french works, spanish works.
Regards from Germany,

**Comment by abbasou** [comment]
Just noticed this as well. Fixed by adding `.replace(/ /g, "")` to:
```
bottom += ((_c = this.settings) == null ? void 0 : _c.bookTagging) ? ` #${this.verseReference.bookName
```
and
```
bottom += ((_d = this.settings) == null ? void 0 : _d.chapterTagging) ? ` #${this.verseReference.bookName
```
in `get bottom()`
Hope that helps.

**Comment by abbasou** [comment]
Pull request submitted to fix this.

**Comment by tim-hub** [comment]
https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.5.2

Fixed here. Credits @abbasou
