### ISSUE TITLE
Option to add nested chapter tags

### ISSUE THREAD

**Issue by BondservantMedia** [tim-hub/obsidian-bible-reference#156]
**Is your feature request related to a problem? Please describe.**
Proliferation of top-level tags for chapters of each book (and it's just a nicer experience with the chapters grouped together under the book tag, as shown below).

**Describe the solution you'd like**
Option in the plugin settings to insert nested tags for chapters,  e.g. `#Romans/1` rather than `#Romans1`.
<img width="908" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/150428149/6df22c11-021e-483f-9be8-888f571ea547">

**Describe alternatives you've considered**
- Naming of nested tags could just be the chapter number (`#Romans/1`), or it could include a prefix like `Romans/Ch1` or `Romans/Chapter1`.
- Nested tags could technically remove the need for having a separate book tag added to passages, since the nested tag will show up in a search for the parent (book) tag as well as a search for the nested tag, but it won't show a connection to the parent tag in the Graph view without having the book tag included separately, like the plugin already allows.

**Additional context**
Using nested tags would allow for chapter tags in the tag browser list to be grouped under their respective book tags and the ability for them to be collapsed. See attached screenshot as an example.
<img width="274" alt="image" src="https://github.com/tim-hub/obsidian-bible-reference/assets/150428149/ae8ded0c-f69d-4606-9a12-b1e685e5039b">

And lastly, thanks for providing this plugin and facilitating a great experience for incorporating Bible quotations into notes in Obsidian!

**Comment by tim-hub** [comment]
Good idea, thanks
