### ISSUE TITLE
Accent Letters not recognized

### ISSUE THREAD

**Issue by saulbravo** [tim-hub/obsidian-bible-reference#159]
Hello and blessings.

**Describe the bug**
á (A with acute) or similar letters cannot be used to insert or search bible verses in obsidian. This is especially true for Spanish language bible verses.

**To Reproduce**

For example type 
--Gálatas1:1
(Galatians in English)
or 
--Génesis1:1
And there is no response.

**Expected behavior**
Would be nice if you could use accent letters but even better if you could use non accent letters to still find the verse.
so --Génesis1:1 or --Genesis1:1 would yield the same result in Spanish or the language used in the settings.

**What Device Do You Use(please complete the following information):**
 - Device: PC Desktop
 - OS: Windows 10 Pro
 - Version 22H2
 - Spanish Nueva Version Internacional @Bolls Life
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/25356481/27a6996d-d401-4120-b24d-6ea30b6d3b97)

**Comment by tim-hub** [comment]
There was a discussion about Interlisation here


https://github.com/tim-hub/obsidian-bible-reference/discussions/77
