### ISSUE TITLE
verse links broken in various epistles

### ISSUE THREAD

**Issue by kdave5** [tim-hub/obsidian-bible-reference#161]
**Describe the bug**
Whenever a verse is chosen from an epistle that is more than one (i.e. 1 or 2 Corinthians, 1 or 2 Peter, etc.) the link formatting for `bible-api.com` links break because of a missing `+` between the number and the epistle.

**To Reproduce**
1. Set verses to include bible-api reference and collapsible
2. Enter verse
3. Deselect verse

**Expected behavior**
The format should be the same as other books of the Bible.

**Screenshots**
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/130889305/121076c5-76fc-4b66-a19d-b20218a98ee0)

**What Device Do You Use(please complete the following information):**
 - Device: PC
 - OS: Windows 10 Pro
 - Version 19045

**Comment by tim-hub** [comment]
This is a bug here. Thanks for the feedback

**Comment by tim-hub** [comment]
@kdave5 Can you double check it with latest build?

I could not reproduce it on my side

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/9e9a1c3c-2941-4f47-9afd-52c7ae4c32a9)

**Comment by kdave5** [comment]
I just tested it after updating the plugin. Works as intended.

Thanks
