### ISSUE TITLE
Link to an online Bible instead of an API

### ISSUE THREAD

**Issue by BravishkaSkytano** [tim-hub/obsidian-bible-reference#164]
I don't understand why a link to the API is in the header. I think it would be better to either remove the link and just display the reference, or link to an online Bible.

**Comment by tim-hub** [comment]
Hi @BravishkaSkytano this could be changed in setting.

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/506273ae-f2a9-4afa-a253-74c878d6e35d)


![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/b7b58150-433b-468d-b331-6a7ffd762916)

**Comment by BravishkaSkytano** [comment]
I saw that, my only problem with it is that it removes the reference (e.g. John 1:1).

**Comment by tim-hub** [comment]
But Link to an online Bible instead of API will be a good idea
