### ISSUE TITLE
Romanian translation RCCV doesnt work anymore

### ISSUE THREAD

**Issue by laurentiucoman** [tim-hub/obsidian-bible-reference#165]
Hello,
 
I've recently tried to make a bible study and i was using this plugin, but for some reason the RCCV romanian translation doesnt work.
It says "undefined".
Thank you in advance for your time!

**Comment by tim-hub** [comment]
Sorry for late reply

**Comment by tim-hub** [comment]
I did some research on the API side, the issue is that the book names, the API does not support use English book name, it requires English short book name like `John` or use Romanian book name `Ioan`.

**Comment by tim-hub** [comment]
What I mean is for this translation, it is a bit different, we can only use short book name or native Romanian book name to trigger.
