### ISSUE TITLE
Add support for german bible names

### ISSUE THREAD

**Issue by blankton2** [tim-hub/obsidian-bible-reference#168]
1. What language are you looking for?
German

2. What version is it?

3. Do you know, is there a public bible API for it?

I wrote the de.json File for https://github.com/Antioch-Tech/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations

Please add that file, so that we can use the german Names.
[de.json](https://github.com/tim-hub/obsidian-bible-reference/files/13836070/de.json)

This is my first time submiting code, please be indulgent :)

**Comment by tim-hub** [comment]
Do you know how to create a PR? :)

**Comment by blankton2** [comment]
Not yet.
I will look into it tomorrow :)

Tim ***@***.***> schrieb am Do., 4. Jan. 2024, 23:32:

**Comment by blankton2** [comment]
I made a PR
