### ISSUE TITLE
Verse Omission or Cutoff

### ISSUE THREAD

**Issue by tim-hub** [tim-hub/obsidian-bible-reference#176]
### Discussed in https://github.com/tim-hub/obsidian-bible-reference/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **hikirnomad** February 14, 2024</sup>
BLuF:

I went to use the "--" function to inject scripture and all seems well, however I noticed that with some books there's a limit or omission depending, when asking for multiple verses. Varying changes to the amount of verses doesn't really change the behavior so long as it is more than the current output > if it is less than the ending amount, then it functions fine. 

Here's the scenario (mobile, desktop app):

--Isaiah58:1-20
--- It doesn't go past 14
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/50116310/0c551c6a-74d3-43b4-a7cc-585a2aacc43e)

Simple adjustment to the verse ending:
---it still doesn't go past 14
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/50116310/82ad9fef-4121-4212-8b8b-9b3f98d84beb)

Choose number less than "14" for ending verse number? Sure thing:
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/50116310/1f6a7f06-c840-4b09-800b-3eacf7a23128)

Does it happen on other books? idk, but it doesn't in Matthew (so far) NT
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/50116310/88a4fbef-d844-4e7e-8032-d6a8dae5338d)
Nor Gen1:1-30 OT
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/50116310/ec24ea3c-e5c6-4487-838a-73be8a9fb9dc)

So not sure; maybe it's a Layer8 problem, but figured I'd ask. 

Thanks for the awesome work!!
</div>

**Comment by AlphaHasher** [comment]
There is no problem. Isaiah chapter 58 does not have more than 14 verses, so there is no point in trying to load more verses since they do not exist.
