### ISSUE TITLE
consistency of lookup by name 

### ISSUE THREAD

**Issue by swuphoto** [tim-hub/obsidian-bible-reference#179]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to use 3 or 4 characters for book's name but it doesn't work.

**Describe the solution you'd like**
1Cor10:1 should render 1Corinthians10:1 without typing the long name, as in Gen1:1

**Comment by AlphaHasher** [comment]
Works fine for me, not sure what your exact setup was @swuphoto, that caused the plugin did not recognize the shortened book title
![Obsidian_RIxs7h2Ams](https://github.com/tim-hub/obsidian-bible-reference/assets/33443001/c95e7686-5bf2-4e57-8982-bb1b492a84c9)
![Obsidian_NdezeHfmM3](https://github.com/tim-hub/obsidian-bible-reference/assets/33443001/ee30d80c-135f-497e-be9d-dce834033855)
