### ISSUE TITLE
期待有中文版出现

### ISSUE THREAD

**Issue by chenxin0397** [tim-hub/obsidian-bible-reference#18]
我曾在社区看到你的这个插件受到启发，我自己把中文圣经转为MD格式临时用了一下但只能实现引用一节或一章的效果，看到你这插件可以自由选择从哪节到哪节非常羡慕，但我的能力有限实现不了，不知道我整理出来的66卷书的MD文件能不能派上用场，请你出一个中文版圣经的插件？

**Comment by tim-hub** [comment]
谢谢反馈 🙏

**Comment by chenxin0397** [comment]
I have seen this plugin of yours inspired in the community. I converted the Chinese Bible into MD format and used it temporarily, but it can only achieve the effect of citing a section or a chapter. Seeing your plugin, you can freely choose which section to choose from. Which section is very envious, but my ability is limited and cannot be realized. I don’t know if the MD files of the 66 volumes that I have sorted out can come in handy. Could you please provide a plug-in for the Chinese version of the Bible?

**Comment by chenxin0397** [comment]
[Chinese Union Version - Simplified Enhanced (简体中文和合本圣经增强版) by Ben Zheng](https://mysword-bible.info:4443/download/getfile.php?file=CUV-e.bbl.mybible.gz) [CUV-e]

**Comment by myjeshurun** [comment]
我也希望能有圣经中文版的插件～
至少可以选择：中文圣经版本CUV，谢谢🙏

**Comment by tim-hub** [comment]
CUV was added

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/1.0.2
