### ISSUE TITLE
Want to add Tamil bible which api availabe in bolls

### ISSUE THREAD

**Issue by ghost** [tim-hub/obsidian-bible-reference#180]
1. What language are you looking for?
Tamil

2. What version is it?
TBSI

3. Do you know, is there a public bible API for it?

Bolls bible api

**Comment by tim-hub** [comment]
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/6e201997-14ba-492f-843f-8a33b094c18c)


![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/1f133f8e-12c1-4f87-a72b-2d891ac790f9)


Planning to add it in the new release

**Comment by tim-hub** [comment]
check release 2.5.0
