### ISSUE TITLE
Switch Bible used from command menu

### ISSUE THREAD

**Issue by jv209** [tim-hub/obsidian-bible-reference#181]
I use two different bibles. One in English and one in Spanish.

There is no quick way of switching the versions other than going to the options page every time.

Would it be possible to mark you favorite bibles and then either:
1. See them in the command modal
2. Or assign a hotkey to switch between my selected favorites.

I am not sure if you would need more than two favorites. But, that would be for others to chime in and discuss.

**Comment by hi-reeve** [comment]
can you please implement this? @tim-hub 
in my cases, when i take notes of a sermon, in my church some pastor uses niv and sometimes they uses nkjv. i think it will be good to add another option to insert reference with the bible selector first?

**Comment by rsmith-osc** [comment]
Perhaps a letter after the verse denoting the version? Like `A` for Amplified for example...

**Comment by tim-hub** [comment]
> can you please implement this? @tim-hub in my cases, when i take notes of a sermon, in my church some pastor uses niv and sometimes they uses nkjv. i think it will be good to add another option to insert reference with the bible selector first?

I would like to do it, the only thing stopped me is that this will be a big change, it need a big chunk of time, I will try to find the time and make it.
