### ISSUE TITLE
MEV Modern English Version

### ISSUE THREAD

**Issue by Goye4th** [tim-hub/obsidian-bible-reference#183]
1. What language are you looking for?
English

2. What version is it?
MEV Modern English Version

3. Do you know, is there a public bible API for it?
Yes, I spoke with the creator and he deployed the translation
Telegram @Boguslavv

**Comment by abbasou** [comment]
This one is as simple as adding the entry in the bolls.life section. User can do it manually if they don't want to wait for dev to implement. Open main.js in plugin folder, search for "New King" to find the bollsLife entries (line ~12448), add the following:
```
  {
    key: "mev",
    versionName: "Modern English Version",
    language: "English",
    code: "en",
    apiSource: BibleAPISourceCollection.bollsLife,
    infoUrl: "https://wikipedia.org/wiki/Modern_English_Version"
  },
```

Save. Restart Obsidian. MEV now appears in the list and works as intended.

**Comment by Goye4th** [comment]
Where do I find the plug ins folder on my Mac - Github?

Thanks!

___

Christian Moore

**Comment by Goye4th** [comment]
When I open the main.js file in the obsidian plugin folder I am not seeing the bollsLife entry line “new king” does not appear in the search nor does “bollLife"

Please advise and thanks for your help!

___

Christian Moore

**Comment by tim-hub** [comment]
@Goye4th will release the change now to add it.

https://github.com/tim-hub/obsidian-bible-reference/pull/196

Thanks @abbasou

**Comment by tim-hub** [comment]
Added in https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.5.2

**Comment by Goye4th** [comment]
Thanks so much!!!

___

Christian Moore

**Comment by Goye4th** [comment]
Hi Tim,I was wondering if you have updated the MEV to the new est MEV 2024 version? If not could i request that?Thanks!___CHRISTIAN MOOREOn May 17, 2024, at 11:01 PM, Tim ***@***.***> wrote:﻿
Added in https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.5.2
