### ISSUE TITLE
Turkish Support Please

### ISSUE THREAD

**Issue by Medullitus** [tim-hub/obsidian-bible-reference#191]
1. What language are you looking for?
Turkish please

3. What version is it?
2.4.5

4. Do you know, is there a public bible API for it?
No

**Comment by tim-hub** [comment]
Hi @Medullitus 

Thanks for the issue.

I couldn't find an API to provide Turkish Bible as well. This plugin is fully dependents on the public API.

I will close this for now, but feel free to re-open it if you want any API for Turkish translation.

Thanks again.
