### ISSUE TITLE
German Neue  Einheitsübersetzung

### ISSUE THREAD

**Issue by Hobbypaedagoge** [tim-hub/obsidian-bible-reference#192]
1. What language are you looking for?

German

2. What version is it?

Neue Einheitsübersetzung (2016)

3. Do you know, is there a public bible API for it?
Unfortunately, since I don't really know much about such things, I found this in an online search. Bibleserver.com is my personal favorite site so far for Bible translations. It's about API, but I don't know if that's what you need to program the plugin.
[Bibleserver](https://www.bibleserver.com/webmasters)

**Comment by tim-hub** [comment]
Hi @Hobbypaedagoge 

I have checked the Bibleserver, it is such a great tool, however, it seems like not providing API for use.

**Comment by tim-hub** [comment]
> Hello Tim,
> thank you for your quick response. I think the site is great too. Of course, it would have been even better if she had also had something for Bible Reference. I'm really not familiar with API at all and have zero knowledge of it. Do sites like https://bibel.github.io help? Or does that not help at all? The Einheitsübersetzung in particular is the standard Bible for Catholic Christians in German-speaking countries. So of course it would be great to have it in Bible Reference. But I can understand if it's not possible, especially with a free to use project like your plugin.
> Best regards
> Hobbypaedagoge

Bible.github.io doesn't provide an API from what I can tell. 😓

**Comment by Ainias** [comment]
Here is the repository list of bibel.github.io: https://github.com/orgs/bibel/repositories?type=all
Not all bibles are available for the public, but some are. As far as I can tell, all the bibles are in the same format. Maybe you could write a parser for the html and add more bibles in one go?

**Comment by tim-hub** [comment]
> Here is the repository list of bibel.github.io: https://github.com/orgs/bibel/repositories?type=all
> Not all bibles are available for the public, but some are. As far as I can tell, all the bibles are in the same format. Maybe you could write a parser for the html and add more bibles in one go? 

This is too much work, I wouldn't say I have time to do it at current stage.
