### ISSUE TITLE
Support CUNPS (Chinese)

### ISSUE THREAD

**Issue by emacsbliss** [tim-hub/obsidian-bible-reference#197]
1. What language are you looking for?

Chinese

2. What version is it?
CUNPS

3. Do you know, is there a public bible API for it?
It's already available with bolls.life, for eg: https://bolls.life/CUNPS/58/10/

**Comment by tim-hub** [comment]
added in version 2.5.3

**Comment by emacsbliss** [comment]
great, thanks a lot!!
