### ISSUE TITLE
Make the Legacy Standard Version of the Bible available in the Plugin

### ISSUE THREAD

**Issue by GinoMan** [tim-hub/obsidian-bible-reference#200]
1. What language are you looking for?

English

2. What version is it?

The Legacy Standard Version - LSV

3. Do you know, is there a public bible API for it?

Yes, bolls.life which is already used by this plugin already supports the Legacy Standard Version under the Version Slug "LSV".

**Comment by AlphaHasher** [comment]
Hello, I added your request into my fork of this repo, it's currently awaiting approval but it does work. https://github.com/AlphaHasher/obsidian-bible-reference

![Obsidian_6PmD0ioRSU](https://github.com/tim-hub/obsidian-bible-reference/assets/33443001/407b38d6-62cc-4676-998d-2d12456f8225)

You will need to download it manually and put the folder in: your vault folder -> .obsidian -> plugins

Let me know if you need any help.

**Comment by tim-hub** [comment]
> Hello, I added your request into my fork of this repo, it's currently awaiting approval but it does work. https://github.com/AlphaHasher/obsidian-bible-reference
> 
> ![Obsidian_6PmD0ioRSU](https://private-user-images.githubusercontent.com/33443001/336216219-407b38d6-62cc-4676-998d-2d12456f8225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NTk5OTgsIm5iZiI6MTcxNzQ1OTY5OCwicGF0aCI6Ii8zMzQ0MzAwMS8zMzYyMTYyMTktNDA3YjM4ZDYtNjJjYy00Njc2LTk5OGQtMmQxMjQ1NmY4MjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDAwMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMDBjMTAyMTI0OWZiMmFjMWYwN2JmYzE3ZjA2YzU2MjdhZTFkYjAxYzk3OThkMDUxODIzMDU4MWQyOGM2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwrqeDZnW55vJT93Xxe9Z8_DOfAIpnfKQFiq_Qi4cDc)
> 
> You will need to download it manually and put the folder in: your vault folder -> .obsidian -> plugins
> 
> Let me know if you need any help.

Thanks I will find time for release it.

**Comment by tim-hub** [comment]
Released in version 2.5.4

**Comment by tim-hub** [comment]
Thanks
