### ISSUE TITLE
API for Turkish translation

### ISSUE THREAD

**Issue by Medullitus** [tim-hub/obsidian-bible-reference#205]
Hello,

In the previous issue I opened, you mentioned that I need to open a new topic if I want an API for Turkish translation. I am not very proficient in the programming language. I have no idea what an API is for. But I need your help as a developer on this matter! Thank you.

**Comment by Medullitus** [comment]
I'm sorry, but I didn't understand. There are many versions of the Bible in various translations available on the internet, including Turkish. Who should we contact to have these translations made into an API?

**Comment by tim-hub** [comment]
> I'm sorry, but I didn't understand. There are many versions of the Bible in various translations available on the internet, including Turkish. Who should we contact to have these translations made into an API?

here it is 
https://aws.amazon.com/what-is/restful-api/
