### ISSUE TITLE
Extra spacing in the Bible verse URL and Tags when entering verse from chapters beginning with number  

### ISSUE THREAD

**Issue by RamchandraWarang9822** [tim-hub/obsidian-bible-reference#208]
**Describe the bug**
When adding the verse from a chapter with a number at beginning like 1 Samuel, 1 Kings ,2 Kings The text which  

**To Reproduce**
1. Go to Obsidian
2. Start typing a chapter name which beings with a number and for the Bible version I am using KJV
3. See error

**Expected behavior**
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/92023869/6d31269d-e90f-46bc-9783-80b6f1263556)

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/92023869/6ea0aad7-08e4-4845-ac59-f677f6e0d5a3)

**Screenshots**
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/92023869/ab50e39f-9fdb-421b-b803-433208f3a53c)

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/92023869/d982502c-02e5-41a1-8a1b-a9023a5c227e)

**What Device Do You Use(please complete the following information):**
 - Device: ASUS TUF gaming A15
 - OS: Windows 11

**Comment by abbasou** [comment]
Can you verify your plugin is up to date? This was address in issue #185 and fixed in release 2.4.5. I just tried it and it works for me, though my links go to BibleGateway, not directly to bible-api.com.
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/68356554/d1be6e40-5c7e-45f3-86a7-3c820a70602b)
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/68356554/c7de9fa7-b696-4ceb-88a4-d9f1cd8767f6)

**Comment by tim-hub** [comment]
> Can you verify your plugin is up to date? This was address in issue #185 and fixed in release 2.4.5. I just tried it and it works for me, though my links go to BibleGateway, not directly to bible-api.com.
> ![image](https://github.com/tim-hub/obsidian-bible-reference/assets/68356554/d1be6e40-5c7e-45f3-86a7-3c820a70602b)
> ![image](https://github.com/tim-hub/obsidian-bible-reference/assets/68356554/c7de9fa7-b696-4ceb-88a4-d9f1cd8767f6)
> 
> The similar issue with the spaces in the tags was also addressed already.

@RamchandraWarang9822 can you confirm your plugin version?

**Comment by RamchandraWarang9822** [comment]
Hey, 
I updated it recently to 2.5.6 
And the issue is no more 

I assume the issue was on my side of not updating 

Thank you very much for creating and maintaining this plugin It has been really helpful 

God bless you ❤️
