### ISSUE TITLE
Reference multiple chapters from a book

### ISSUE THREAD

**Issue by cvasanthk** [tim-hub/obsidian-bible-reference#212]
**Is your feature request related to a problem? Please describe.**
In a note, for example type --John1-2. The chapters 1-2 to be viewed. Currently this is not working. 

**Describe the solution you'd like**
The Chapter to be rendered collapsible  with the Bible Icon Prefix enabled either all together i.e, Chapter 1&2 together or as collapsible chapter wise when  --John1-2 is specified. 

**Describe alternatives you've considered**
I do a guess work on the number of verses and iterate --John1:1-35 and then add another line for --John2:1-30

**Additional context**
I need to reference the daily reading plan by combining chapters and not just verses.

**Comment by tim-hub** [comment]
This is a good idea, however there are two issues here

1. the happening of API failing will be increased.
2. Bible API does not support whole chapter, bills life support it.
