### ISSUE TITLE
Support for tamil bible and Option to import sermons and Sync Sermons

### ISSUE THREAD

**Issue by mangoose20026** [tim-hub/obsidian-bible-reference#213]
1. Add support as well as a new page for tamil bible like English (https://bolls.life/) to search and read online. Tamil bible is available in all formats whichever you like to use (https://github.com/godlytalias/Bible-Database/tree/master/Tamil)
2. Add support to import sermon text files to search like how we search the bible. That would be really helpful. (For example, import spurgeon sermon text files, import John Bunyan sermons files, import Calvin Sermon files)
3. Add support to Sync sermon text files from website folder link or shared folder link. That would be really helpful. (For example, spurgeon sermon text files placed in a website in a folder, John Bunyan sermons files placed in a website in a folder, import Calvin Sermon files placed in a website in a folder)

**Comment by ajwdd** [comment]
Is the Tamil Older Version Bible (TBSI) good? That's on https://bolls.life/TBSI/1/1/ and I could make a pull request to add it.
As for the sermons could you provide an example? An issue may be the lack of formatting in sermon texts.

**Comment by mangoose20026** [comment]
It is good...either you can pickit from  https://bolls.life/TBSI/1/1/  or
use  (https://github.com/godlytalias/Bible-Database/tree/master/Tamil

**Comment by tim-hub** [comment]
Can you explain more what is the use case of syncing?
And how do you want to use it?
