### ISSUE TITLE
Doesn't always work

### ISSUE THREAD

**Issue by jmcd040** [tim-hub/obsidian-bible-reference#217]
I started a line with ```++2 Cor. 5:1-4``` and nothing happened. I've opened the plugin using the icon in the sidebar and typed ```2 Cor. 5:1-4```, but again nothing happens. I retyped ```2Cor5:1-4``` in the text entry field and got a result. However, typing that on a line (```++2Cor5:1-4```) still didn't work. On the other hand, sometimes typing references without spaces and periods does work and other times it does not. The plugin seems very inconsistent. This wastes time and interrupts my writing flow as I deal with it.

Often I copy a reference from somewhere and paste it into a new note where I want the reference expanded to show the text. So I think it would be good to expand your flexibility. I wouldn't mind having to highlight the reference if it is too hard to grab it as it is being typed when there are spaces.

If I'm doing something wrong, please let me know.

I do appreciate that you have added many Bible versions and do appreciate the plugin since theoretically, it can save me time in writing sermons and articles.

**Comment by tim-hub** [comment]
Can you give me more details?

What OS you are using?
What version are you using?and which translation.

There is a rate like for the Bible API, it could be the reason why it stopped working.

If you know how to use developer tool, would you mind sharing the logs when the issue happens?

**Comment by rsmith-osc** [comment]
Similar, `2 Co` works but `2 Corin` or `2Cor.` doesn't

**Comment by tim-hub** [comment]
> Similar, `2 Co` works but `2 Corin` or `2Cor.` doesn't

https://github.com/Antioch-Tech/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations

**Comment by jmcd040** [comment]
> Can you give me more details?
> 
> What OS you are using? What version are you using?and which translation.
> 
> There is a rate like for the Bible API, it could be the reason why it stopped working.
> 
> If you know how to use developer tool, would you mind sharing the logs when the issue happens?

Sorry for the delay. I'm using Win11. Plugin is currently at 3.1.0 which could have been updated since my post. I'm using NASB95 Bible version.

**Comment by tim-hub** [comment]
> > Can you give me more details?
> > 
> > What OS you are using? What version are you using?and which translation.
> > 
> > There is a rate like for the Bible API, it could be the reason why it stopped working.
> > 
> > If you know how to use developer tool, would you mind sharing the logs when the issue happens?
> 
> Sorry for the delay. I'm using Win11. Plugin is currently at 3.1.0 which could have been updated since my post. I'm using NASB95 Bible version.
> 
> ++2Cor.5:15 does not work
> 2 Co 5:15 does work
> 

We does not support Co, 

It is not really decision from me, because CO is not really an abbreviation in English.

Because some people may think CO represents Corinthians, others may think Colossians.

This potentially increased confusion.

This is why, I hope this explanation helped.
