### ISSUE TITLE
other languaes support of book names

### ISSUE THREAD

**Issue by chrisdong** [tim-hub/obsidian-bible-reference#219]
it's an awesome plugin for Christian when using Obsidian

the plugin only surpport Bible book name in English.  if it surpport other languages, it would be benifit to Christians all over the world.
 the translation of book name can be found in Youversion website

in China ，we use 太 for short  instead of 马太福音 , when write, for example
太1:5-6 means Matthew1:5-6
or 马太福音1:5-6，full book name, when we say the book name

Most Chinese in China cannot write or say Bible book names in English. If this plugin support book name in Chinese, that would be great

**Comment by chrisdong** [comment]
most Chinese speakers uses simplified Chinese when write,  other uses traditional Chinese.  Chinese Union Version Bible(CUNPSS) is used mostly in Chinese speakers

**Comment by chrisdong** [comment]
![PixPin_2024-07-23_16-10-50](https://github.com/user-attachments/assets/7aa4375a-2d2d-4410-9572-7094f6568de0)

**Comment by chenxin0397** [comment]
我也碰到相同的问题了，想了解66卷书的简写，但哥林多前后书这样的书卷简写总是不成功，请问能不能公示一下所有的简写列表？

**Comment by tim-hub** [comment]
> 我也碰到相同的问题了，想了解66卷书的简写，但哥林多前后书这样的书卷简写总是不成功，请问能不能公示一下所有的简写列表？

All books' translations are here, 

https://github.com/Antioch-Tech/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations

**Comment by MathiasRenoult** [comment]
I also would like to use book names in other languages. I already made a json file with french book names and abbreviations. But atm the project doesn't seem to support other languages. I don't think that I would be able to add this feature in the plugin myself, however I would be happy to provide my french translation.

**Comment by tim-hub** [comment]
> I also would like to use book names in other languages. I already made a json file with french book names and abbreviations. But atm the project doesn't seem to support other languages. I don't think that I would be able to add this feature in the plugin myself, however I would be happy to provide my french translation.

It is OK, 
Can you try to follow [the same format](https://github.com/Antioch-Tech/bible-reference-toolkit/tree/master/packages/bible-book-names-intl/src/data/translations) to update your JSON file here?

**Comment by MathiasRenoult** [comment]
I used this format but I can't upload the file there. Where should I upload it ? Or, am I missing something ?

**Comment by tim-hub** [comment]
> I used this format but I can't upload the file there. Where should I upload it ? Or, am I missing something ?

You can leave a comment and drag your file in it. 😄

**Comment by MathiasRenoult** [comment]
Here it is ! Thx for your help.
[fr.json](https://github.com/user-attachments/files/16962276/fr.json)

**Comment by chenxin0397** [comment]
> [zh-CN.json](https://github.com/user-attachments/files/16965215/zh-CN.json)
> 
> simplified Chinese
> 
> how to use this json file in obsidian plugin ?
> 
> 
是弟兄吗？加个联系方式？

**Comment by chenxin0397** [comment]
> > I used this format but I can't upload the file there. Where should I upload it ? Or, am I missing something ?
> 
> You can leave a comment and drag your file in it. 😄

中文的Json文件已经上传了，盼望您尽快更新中文调用的功能

**Comment by chrisdong** [comment]
> > [zh-CN.json](https://github.com/user-attachments/files/16965215/zh-CN.json)
> > 
> > simplified Chinese
> > 
> > how to use this json file in obsidian plugin ?
> > 
> > 
> 是弟兄吗？加个联系方式？

WeChat : chrisd

**Comment by tim-hub** [comment]
> Here it is ! Thx for your help. [fr.json](https://github.com/user-attachments/files/16962276/fr.json)

Please try



> [zh-CN.json](https://github.com/user-attachments/files/16965215/zh-CN.json)
> 
> simplified Chinese
> 
> how to use this json file in obsidian plugin ?

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/3.2.0

**Comment by chrisdong** [comment]
thank you so muc ! it works 


> > Here it is ! Thx for your help. [fr.json](https://github.com/user-attachments/files/16962276/fr.json)
> 
> Please try
> 
> 
> 
> > [zh-CN.json](https://github.com/user-attachments/files/16965215/zh-CN.json)
> > 
> > simplified Chinese
> > 
> > how to use this json file in obsidian plugin ?
> 
> https://github.com/tim-hub/obsidian-bible-reference/releases/tag/3.2.0

**Comment by chenxin0397** [comment]
> > Here it is ! Thx for your help. [fr.json](https://github.com/user-attachments/files/16962276/fr.json)
> 
> Please try
> 
> > [zh-CN.json](https://github.com/user-attachments/files/16965215/zh-CN.json)
> > simplified Chinese
> > how to use this json file in obsidian plugin ?
> 
> https://github.com/tim-hub/obsidian-bible-reference/releases/tag/3.2.0

这个版本里错了一个字，请修改一下：“贴”下，正确的写法是“帖”下
