### ISSUE TITLE
Plugin Settings Page is blank.

### ISSUE THREAD

**Issue by Redster1** [tim-hub/obsidian-bible-reference#225]
The settings page for the plugin is blank except for the sponsor button.

![image](https://github.com/user-attachments/assets/7156b7cc-28e3-44f0-a283-c6b4b87783a0)

When I open the console, this error message appears and seems relevant. 
```
VM343 plugin:obsidia…ble-reference:12979 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isFeatureEnabled')
    at BibleReferenceSettingTab.setUpVersionSettingsAndVersionOptions (VM343 plugin:obsidia…-reference:12979:50)
    at BibleReferenceSettingTab.display (VM343 plugin:obsidia…-reference:12848:10)
```

That seems related to this function here: 
```
  setUpVersionSettingsAndVersionOptions() {
    let allAvailableVersionOptions = allBibleVersionsWithLanguageNameAlphabetically;
    const disableBibleAPI = FlagService.instance.isFeatureEnabled("disable-bible-api");  //  <-- This line specifically as the .isFeatureEnabled is flagged as having an error.
    if (disableBibleAPI) {
      allAvailableVersionOptions = allAvailableVersionOptions.filter((v) => {
        return v.apiSource.name !== BibleAPISourceCollection.bibleApi.name;
      });
    }
```

 - Device: Lenovo Thinkpad T480
 - OS: Windows 10
 - Obsidian Version : v1 .7.1 (Installer version: V1 .5.12) 
 - Plugin Version: v3.1.1

![image](https://github.com/user-attachments/assets/f42ac6d4-01a6-41e4-90a5-90940657f445)

I probably wouldn't have worried about reporting this, but it switched Bible versions on me and I can't switch translations. 

- I'm on the default Obsidian Theme and have no other plugins installed.
- Tried uninstalling and reinstalling the plugin. 
- Not sure when this started. 

Happy to poke around and try to help in any way I can or provide more info.  

Thanks so much for this awesome plugin. I love it.  It's been super helpful as I've been working on a research project on the conscience.

**Comment by tim-hub** [comment]
Thanks, I can see it in one of my computers as well, let me fix it.

**Comment by tim-hub** [comment]
It is fixed in 3.1.2, can you have a try?

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/3.1.2

**Comment by tim-hub** [comment]
@all-contributors add @Redster1  for bug

**Comment by Redster1** [comment]
It's fixed! 🎉 
Thank you so much!
