### ISSUE TITLE
hope that traditional Chinese will be added to this awesome plugin

### ISSUE THREAD

**Issue by chrisdong** [tim-hub/obsidian-bible-reference#235]
There 2 kinds of Chinese  Characters. 

I made zh-CN.json file, simplified Chinese ,which is used among  people in China Mainland ,Singapore and Maylaysia.

and zh-TW.json , Traditional Chinese ,which is used among people in Taiwan, Hong Kong, Macao.

traditional Chinese bible is here. https://www.bible.com/zh-TW/bible

hope Traditional Chinese will be added to this awesome plugin
[zh-TW.json](https://github.com/user-attachments/files/17161092/zh-TW.json)

**Comment by tim-hub** [comment]
Thanks, these will be included in next release, planned on early next month.

**Comment by tim-hub** [comment]
Please check this release https://github.com/tim-hub/obsidian-bible-reference/releases/tag/3.2.1
