### ISSUE TITLE
Program doesn't work.

### ISSUE THREAD

**Issue by ShayneWilliams** [tim-hub/obsidian-bible-reference#246]
**Describe the bug**

**To Reproduce**
1. Go to ' just open the "Bible Verse Reference" as either the Geneva Bible, or King James Bible API, possibly others'
2. Try to search up any verses, and it won't work

**Expected behavior**
It should allow verses to show up for me to click. When I first installed the program it worked a few weeks ago, now it doesn't. I've updated it repeatedly, uninstalled and reinstalled it, tried multiple different settings, it doesn't work. If the api is not working, if possible it'd be nice if we could use a local api or if it could somehow be packaged with the bible verses locally as an option so that this is avoidable.

**Screenshots**
![broken bible reference](https://github.com/user-attachments/assets/83829776-aa25-49e1-88e9-c9b2ef2bdee7)

**What Device Do You Use(please complete the following information):**
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-26-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD Ryzen 5 4500U with Radeon Graphics
Memory: 15.0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: LENOVO
Product Name: 81X2
System Version: IdeaPad Flex 5 14ARE05

**Comment by Benedictteo05** [comment]
were you able to query a single verse?

**Comment by moltra** [comment]
Is your formatting correct.  Try --john3:16. I think you forgot the chapter.

**Comment by ShayneWilliams** [comment]
Sorry about that, I was formatting it incorrectly thank you so much!

**Comment by moltra** [comment]
> Sorry about that, I was formatting it incorrectly thank you so much!

You are welcome.
