### ISSUE TITLE
reflect two issues 反映两个问题

### ISSUE THREAD

**Issue by chenxin0397** [tim-hub/obsidian-bible-reference#26]
The Chinese version is only in traditional Chinese, which is not suitable for users in mainland China. I hope to have a simplified version soon.
The Chinese version currently has spaces between each Chinese character, please delete

中文版只有繁体中文，不适合中国大陆用户。我希望尽快有一个简化版本。
中文版目前每个汉字之间有空格，请删除

**Comment by chenxin0397** [comment]
中文版只有繁體中文，不適合中國大陸用戶。我希望盡快有壹個簡化版本。  
中文版目前每個漢字之間有空格，請刪除

**Comment by tim-hub** [comment]
Thanks for the feedback.😂
I will keep an eye for finding the CUV Simplify Chinese version.

At current stage, I didn't find a proper Chinese CUV bible API. 😭

**Comment by chenxin0397** [comment]
Hi, the CUV version of the Bible is in Traditional Chinese. Most of China has been using Simplified Chinese for 90 years, and many people born after the 1980s in mainland China have some degree of difficulty reading Traditional Chinese. Traditional Chinese is still commonly used in Hong Kong and Taiwan. Please consider adding a Simplified Chinese version.

Another issue is that both Simplified and Traditional Chinese do not use spaces to separate each Chinese character, which is not suitable for Chinese speakers. Please consider fixing this issue.

**Comment by tim-hub** [comment]
> Hi, the CUV version of the Bible is in Traditional Chinese. Most of China has been using Simplified Chinese for 90 years, and many people born after the 1980s in mainland China have some degree of difficulty reading Traditional Chinese. Traditional Chinese is still commonly used in Hong Kong and Taiwan. Please consider adding a Simplified Chinese version.
> 
> Another issue is that both Simplified and Traditional Chinese do not use spaces to separate each Chinese character, which is not suitable for Chinese speakers. Please consider fixing this issue.

I just checked the API. @chenxin0397 for this space rendering issue.

![image](https://github.com/tim-hub/obsidian-bible-reference/assets/2884320/75df251a-3772-4bb5-ad6f-c2cbabfe0bdf)

It is not very safe to remove the space in between each characters/words in Chinese, because the API return them with space.

**Comment by tim-hub** [comment]
For the work update, 

I did some check online, I could not find one for CUV (simplified Chinese), if you can find something to share about API please let me know. @chenxin0397 

Thanks, for now I will leave this as closed
