### ISSUE TITLE
add indonesian bible 

### ISSUE THREAD

**Issue by hi-reeve** [tim-hub/obsidian-bible-reference#27]
hi, thankyou for the plugin. have you consider to add another bible version? i would love to have indonesia bible included. i can open pr too.

**Comment by tim-hub** [comment]
Thanks, sounds good, I agree that we should bring more language versions to the plugin

**Comment by zynth17** [comment]
> Thanks, sounds good, I agree that we should bring more language versions to the plugin

thanks!

**Comment by zynth17** [comment]
hello, please add this, i really need this with my obsidian

**Comment by tim-hub** [comment]
> @tim-hub just in case you need more api, i have a simple bible api based on scripture api and i'm hosting it myself you can checkout [bible-api](https://github.com/zynth17/bible-api)

Thanks for referring the api, will try add it during xmas time

**Comment by zynth17** [comment]
> > @tim-hub just in case you need more api, i have a simple bible api based on scripture api and i'm hosting it myself you can checkout [bible-api](https://github.com/zynth17/bible-api)
> 
> Thanks for referring the api, will try add it during xmas time

yes please, thankyou.

**Comment by tim-hub** [comment]
> > > @tim-hub just in case you need more api, i have a simple bible api based on scripture api and i'm hosting it myself you can checkout [bible-api](https://github.com/zynth17/bible-api)
> > 
> > Thanks for referring the api, will try add it during xmas time
> 
> yes please, thankyou.

Sorry for the delay,  😅😅

It is in Todo list, will try find time to do it.
