### ISSUE TITLE
或许能用得上

### ISSUE THREAD

**Issue by chenxin0397** [tim-hub/obsidian-bible-reference#28]
https://wdbible.app/1co.11.cunps
这里有很多中文圣经，不知道您是否可以和开发者联系获取API的事

**Comment by tim-hub** [comment]
Thanks

**Comment by tim-hub** [comment]
I just created a task for this

**Comment by chenxin0397** [comment]
I can provide the text files of the simplified Chinese version of the Bible and wonder if you can call them up?
