### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Gloria-hue** [tim-hub/obsidian-bible-reference#29]
Requesting for your kind assistance with adding a vry popular version of the bible. The new world translationVersion.

**Comment by tim-hub** [comment]
Thanks, let me create a task for this

**Comment by tim-hub** [comment]
@Gloria-hue 

I couldn't find an online API for it, do you know any?

**Comment by Gloria-hue** [comment]
> 

gh repo clone cshung/JwBibleDownloader
 hi again ? I think the above is similar to what you are doing ;he might have a proper API? I confess , I don't really know how to get one...but I hope you get it. (The one I pasted on earlier is suspiciously wrong)
