### ISSUE TITLE
[Feature Request] Ideas for settings. 

### ISSUE THREAD

**Issue by thecookiemomma** [tim-hub/obsidian-bible-reference#3]
I'm using this plugin through BRAT and I'm loving it already. I realize it's in a state of development, but I wanted to suggest two things (which you may have already thought of).  
1. Firstly, being able to pick version. I love the fact that you used NKJV, because that seems like a good, solid, middle of the ground version. However, I sometimes want a verse in a different version.  I am not sure how you'd do this, but it's a suggestion. 
2. Secondly, I'd like to be able to format my verse grab, much as other plugins do, e. g. Podcast notes and several others.  I know this may take a lot of work, but being able to format the verse would be very nice. 
I do want to reiterate that I'm already loving this plugin and look forward to see where you take this.  I appreciate all the hard work you've already put into it.  
Thank you.

**Comment by tim-hub** [comment]
Thanks for the feedback, I appreciate it.

**Comment by Obadiahcruz** [comment]
I agree I'm also very excited for the possibilities! Being able to use different versions and change formatting are what I'm looking forward to as well!

**Comment by tim-hub** [comment]
Thanks, again, will make a plan for it

**Comment by tim-hub** [comment]
Three versions should be supported in the setting in release 0.1.3

**Comment by Obadiahcruz** [comment]
ah! i didnt see this update as soon as it came out! You should definitely put it in the updates channel in discord that way new people this winter know about this plugin as well !

**Comment by Obadiahcruz** [comment]
Glad to see you made it to the starboard today!

**Comment by tim-hub** [comment]
> Glad to see you made it to the starboard today!

Thanks, I just saw the starboard
