### ISSUE TITLE
Adding more scripture API

### ISSUE THREAD

**Issue by Saorsa32** [tim-hub/obsidian-bible-reference#33]
I was able to make it work.

**Comment by tim-hub** [comment]
Hi @Saorsa32 

Which API are u suggesting, do you have the API doc/url? :) 

Thanks

**Comment by Saorsa32** [comment]
I wanted to add the LDS Scriptures, Here is a link to the page with the information I have. https://scriptures.nephi.org/ I was able to get what I needed to work, by downloading the Markdown version and using the Bible linker plugin. But maybe you would be able to to make it work with your plugin. Thanks
