### ISSUE TITLE
Add German Bible translation

### ISSUE THREAD

**Issue by daribock** [tim-hub/obsidian-bible-reference#35]
Hello everyone, first of all thanks for the plugin @tim-hub, its really helpfull. It would be even nicer if we could add a german bible translation. Is this possible?

**Comment by tim-hub** [comment]
Hi @daribock 

Thanks for the feedback the only issue is I don't know whether there is a free online German bible API

**Comment by daribock** [comment]
> Hi @daribock
> 
> Thanks for the feedback the only issue is I don't know whether there is a free online German bible API

I think I found one but you need to register for this API. https://scripture.api.bible/
I am not that experienced with API's thats why I why I can't tell you if we could easily implement the API in the obsidian plugin. 🤔

**Comment by daribock** [comment]
Also one other question @tim-hub. How did you build you portfolio page? (https://techtim42.com/) I think it looks really nice and I would love to know how you build it. 🤓

**Comment by tim-hub** [comment]
> Also one other question @tim-hub. How did you build you portfolio page? (https://techtim42.com/) I think it looks really nice and I would love to know how you build it. 🤓

Thanks, Glad to hear you like it.

It is a very simple Nextjs project. 

I haven't make the source code public yet, but if you are familiar with React/Nextjs, I don't mind sharing you with the access to the private repo, so you can have a look and build your own :) 

Just let me know

**Comment by daribock** [comment]
I am familiar with React and Nextjs is on my todo list. 
So yeah I would love to have a sneak peak in your portfolio repo. :D

**Comment by tim-hub** [comment]
> I am familiar with React and Nextjs is on my todo list. So yeah I would love to have a sneak peak in your portfolio repo. :D

I just added you.

https://github.com/tim-hub/techtim42
