### ISSUE TITLE
No space between sentences

### ISSUE THREAD

**Issue by PolymathCrowsbane** [tim-hub/obsidian-bible-reference#37]
I'm not sure if this is a feature or a bug. When the Bible reference appears, there are no spaces between sentences (e.g., This is Sentence One.This is Sentence Two). Is this a function of the API (Bolls)?

Thanks for a great plug-in,
Robert

**Comment by tim-hub** [comment]
Thanks for the feedback, it might be a bug, I will have a look, this wekk

**Comment by tim-hub** [comment]
this would be fixed in version 1.1.0
