### ISSUE TITLE
Verse of the day syntax

### ISSUE THREAD

**Issue by david0x00** [tim-hub/obsidian-bible-reference#40]
I would like to be able to generate a verse of the day in the top of my daily note using templator.

I feature allowing this would be really neat

**Comment by tim-hub** [comment]
Thanks @david0x00 

This is a really good suggestion.

**Comment by JPT62089** [comment]
@tim-hub, It looks like there are a few sources that we can pull from to get a VotD

- https://ourmanna.readme.io/reference/get-verse-of-the-day
- https://theysaidso.com/api/bible/
- https://www.biblegateway.com/usage/votd/docs/
