### ISSUE TITLE
ESV Proverbs do not import correctly

### ISSUE THREAD

**Issue by david0x00** [tim-hub/obsidian-bible-reference#41]
Import a block of proverbs. 

Only the first two lines are included in the block.

*update - actually I think it is the default English Word Bible and not ESV

**Comment by tim-hub** [comment]
Like this?

![image](https://user-images.githubusercontent.com/2884320/178080603-ee8bc5ea-93f9-435a-9d88-3e12e6c975e1.png)


Thanks for the feedback, it is due to the different formating of proverbs, will have a look

**Comment by thecookiemomma** [comment]
KJV does it too.

**Comment by mikolertesx** [comment]
I can confirm it's still an issue.
