### ISSUE TITLE
[Feature] Customize output

### ISSUE THREAD

**Issue by thecookiemomma** [tim-hub/obsidian-bible-reference#43]
Thank you so much for your work on this. I do have a request. I'd like to be able to customize the output of the verses. I have a [!verse] callout that I'd like to be able to use.  Also, I'd like the verse reference in the title of the callout.  Thanks again!

**Comment by tim-hub** [comment]
This issue supposed to be fixed now. in the latest version of the plugin.

![image](https://user-images.githubusercontent.com/2884320/216808052-dad8da8e-030b-4c34-a05b-e92da990529b.png)
