### ISSUE TITLE
New callouts breaks multi-verse insertion

### ISSUE THREAD

**Issue by pastorryanhayden** [tim-hub/obsidian-bible-reference#49]
Recently I upgraded and while I love the look of the new Bible callout feature, it breaks multi-verse insertion on my translation (KJV).

![CleanShot 2022-07-24 at 08 22 21](https://user-images.githubusercontent.com/4194905/180648989-83265e16-b7da-4aba-be98-2dd5c04a8b2a.gif)

If you need help on this, I'd be glad to try to help.  I just need to dig in to figure out how this is working.

**Comment by tim-hub** [comment]
Thanks for the feedback, this is surely a bug, will have a look

**Comment by pastorryanhayden** [comment]
@tim-hub That was fast - thank you so much for making this.  It truly makes my life easier every day.
