### ISSUE TITLE
[Feature Request] Paste link along with Reference

### ISSUE THREAD

**Issue by Obadiahcruz** [tim-hub/obsidian-bible-reference#5]
Would be nice to be able to have an external link pasted with the reference and bible version once you tackle the other requests! 

I dont know if you use macOs but there are alfred workflows that do this

Thank you for your hard work!

**Comment by tim-hub** [comment]
Sounds a good idea, I like it

**Comment by tim-hub** [comment]
Add a basic reference into the plugin in the version 0.1.5

![image](https://user-images.githubusercontent.com/2884320/145337789-7343f3d6-86e9-4c82-bb95-0a1d7d76a8d0.png)

**Comment by tim-hub** [comment]
Feel free to leave comments if you have any more ideas. :) And thanks for the feedback
