### ISSUE TITLE
Put reference at top 

### ISSUE THREAD

**Issue by tim-hub** [tim-hub/obsidian-bible-reference#52]
- [ ] maybe build a setting for it

**Comment by SamejSpenser** [comment]
> * [ ]  maybe build a setting for it

I agree. Adding this possibility in the settings seems to me to be the most appropriate.

Particularly speaking, I usually make this change manually, including also the numbers of the verses.

I am Brazilian and I use the “João Ferreira de Almeida” version, and the result of my manual edition is like this:

![image](https://user-images.githubusercontent.com/14796034/181105848-c211ae77-b769-44b7-8f0b-a37281082fd2.png)

In printscreen we have Matthew 1:1 in the current standard format (`v1.1.4`) and John 1:1-5 with my manual edition.

```markdown
> [!Bible] [João 1:1-5 • ALMEIDA](https://bible-api.com/joao+1:1-5?translation=almeida)
> <small><sup>1</sup></small> No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.
> <small><sup>2</sup></small> Ele estava no princípio com Deus.
> <small><sup>3</sup></small> Todas as coisas foram feitas por intermédio dele, e sem ele nada do que foi feito se fez.
> <small><sup>4</sup></small> Nele estava a vida, e a vida era a luz dos homens;
> <small><sup>5</sup></small> a luz resplandece nas trevas, e as trevas não prevaleceram contra ela. 
```

**Comment by tim-hub** [comment]
> > * [ ]   maybe build a setting for it
> 
> I agree. Adding this possibility in the settings seems to me to be the most appropriate.
> 
> Particularly speaking, I usually make this change manually, including also the numbers of the verses.
> 
> I am Brazilian and I use the “João Ferreira de Almeida” version, and the result of my manual edition is like this:
> 
> ![image](https://user-images.githubusercontent.com/14796034/181105848-c211ae77-b769-44b7-8f0b-a37281082fd2.png)
> 
> In printscreen we have Matthew 1:1 in the current standard format (`v1.1.4`) and John 1:1-5 with my manual edition.
> 
> ```gfm
> > [!Bible] [João 1:1-5 • ALMEIDA](https://bible-api.com/joao+1:1-5?translation=almeida)
> > <small><sup>1</sup></small> No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.
> > <small><sup>2</sup></small> Ele estava no princípio com Deus.
> > <small><sup>3</sup></small> Todas as coisas foram feitas por intermédio dele, e sem ele nada do que foi feito se fez.
> > <small><sup>4</sup></small> Nele estava a vida, e a vida era a luz dos homens;
> > <small><sup>5</sup></small> a luz resplandece nas trevas, e as trevas não prevaleceram contra ela. 
> ```

Thanks for sharing, this looks much better.

**Comment by tim-hub** [comment]
I just add the changes you made to a new branch sept2022. Thanks
