### ISSUE TITLE
New Living Translation and Message Version of the Bible

### ISSUE THREAD

**Issue by profOke** [tim-hub/obsidian-bible-reference#53]
I appreciate the great work you are doing & definitely the world is getting better by your approach to life.
Kindly add these versions of the Bible: New Living Translation and the Message Bible.
Thank you Ma and Sir.

**Comment by tim-hub** [comment]
Thanks for the suggestion, I like NLT as well, 

I didn't know which API provides NLT version. so may need to figure our that first before add more versions
