### ISSUE TITLE
Allows multiple bibleVersion

### ISSUE THREAD

**Issue by ickc** [tim-hub/obsidian-bible-reference#54]
Would you consider allowing multiple bibleVersions?

E.g. selecting `cuv, esv` which will convert the same reference to both translation at the same time.

**Comment by tim-hub** [comment]
Actually it is a good idea, but need some investigation for the implementation

**Comment by jimpfaff** [comment]
I would like to reassert this issue as a request. Could you program it to have a default version but then allow for adjustment of a preferred version when typing it out in this manner:

**Calling the default version:**

--John1:1-4

**Calling out a specified version as needed**

--John1:1-4,NTGT

I often want to add Greek text when I taking notes to compare to the English text. This is helpful for future reference to the note.

**Comment by junwhuan** [comment]
I would like to have this feature as well. Is there any active development on this issue?
