### ISSUE TITLE
[Feature] Formatting options

### ISSUE THREAD

**Issue by JPT62089** [tim-hub/obsidian-bible-reference#57]
Amazing plugin! I would love to use it, however, I would really like to be able to alter the formatting a bit. Would it be possible to add options for splitting the verses to new lines as well as having the verse numbers?

![image](https://user-images.githubusercontent.com/1808107/192199923-789e1bed-1f25-454c-aea8-8413ce0b59e1.png)

**Comment by JPT62089** [comment]
did a quick and dirty adding of formatting options. see PR #58

**Comment by tim-hub** [comment]
Thanks for the PR

**Comment by JPT62089** [comment]
Absolutely! I love working on this type of thing, I used to have a similar type program in Second Life that allowed users to quote verses in chat tho that was some 10 years ago now... Man does that make me feel old... xD
