### ISSUE TITLE
Confusing trigger for Isaiah

### ISSUE THREAD

**Issue by aknisly** [tim-hub/obsidian-bible-reference#79]
Thanks very much for developing this plugin! I use it extensively in my sermon preparations.
One thing that I've encountered--and only now discovered the work-around--is that typing in _--Isa_ triggers 1 Samuel instead of Isaiah. I just discovered that I can type in the _--Isaiah_, so there's no show-stopper here. 
It's possible that documentation is the best resolution, although I don't use the Roman numeral designation myself (e.g, ICor/iCor instead of 1Cor). One other possible solution is to set this as a preference; something like: 

> Triggers for multiple books (e.g., Samuel and Chronicles):
> - [ ] Arabic numerals
> - [ ] Lower case Roman numerals
> - [ ] Upper case Roman numerals

Again, not a show-stopper, but something to consider.

**Comment by tim-hub** [comment]
This should be fixed in version 2.2.0, Thanks for the patience.

https://github.com/tim-hub/obsidian-bible-reference/releases/tag/2.2.0
