### ISSUE TITLE
Extend the verse lookup command

### ISSUE THREAD

**Issue by tim-hub** [tim-hub/obsidian-bible-reference#80]
I am thinking of instead of using `verse lookup` as command

maybe extend to `bible book chapter verse` to be more direct

_Originally posted by @tim-hub in https://github.com/tim-hub/obsidian-bible-reference/issues/78#issuecomment-1434366662_

So that the flow will be like.

- CMD + P 
- John1:1  or ESVJohn1:1

to get the verse, 

instead of 

- CMP + P
- Verse Lookup
- John1:1

**Comment by OfficerHalf** [comment]
I feel like this breaks the convention of how Obsidian's commands work; if you wanted to accomplish this you could with the command as is, just bind it to a keyboard shortcut. What extra convenience would it provide?

**Comment by OfficerHalf** [comment]
I also don't think this would be mobile friendly. With the normal command you can add it to the mobile toolbar. With this sort of custom command flow, I'm not sure you could.

**Comment by chrisg32** [comment]
> I feel like this breaks the convention of how Obsidian's commands work; if you wanted to accomplish this you could with the command as is, just bind it to a keyboard shortcut. What extra convenience would it provide?

I agree. If you want to remove a step then assigning verse lookup as a hotkey solves that, i.e.:
- CMD + R
- John1:1

**Comment by tim-hub** [comment]
@chrisg32 @OfficerHalf 

You are right, will close this for now.
