### ISSUE TITLE
We should have a bare bone verse block formatting option for users. (Minimal version)

### ISSUE THREAD

**Issue by tim-hub** [tim-hub/obsidian-bible-reference#82]
### Discussed in https://github.com/tim-hub/obsidian-bible-reference/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **ajrty33** January  6, 2023</sup>
I have been modifying src/VerseSuggesting.ts to create a minimal version. When taking notes in class with a lot of Scripture references, it's nice to have a bare bones verse without anything else. I would love to create a pull request for this, but creating the settings to make this an option is above my head.
![image](https://user-images.githubusercontent.com/1326379/210857873-098c45b1-1be7-4ac4-9946-6a5408d037b5.png)
</div>

---

- update setting page to organise the setting better, maybe have some screenshot/tutorial gif to show people how settings work
- investigate bare bone verse block, maybe use it as default setting

**Comment by Kilarin** [comment]
I would like to add my voice to this request.

obsidian-bible-reference is an absolutely WONDERFUL tool, thank you for it.

But it would be even more useful to me if there were an option to eliminate the [!Bible] tag AND the url.  I work in prison ministry and I often transfer bible study notes from obsidian to Securus.  Securus is, essentially, an email system for the prisoners in the Texas prison system.  It is very simple, of course, and only allows text.  No fancy formatting, and no mark down.  Of course, one of the beautiful things about markdown is that the vast majority of it makes perfect sense as plain text.  When I copy bible study notes from obsidian into Securus for an inmate, this makes perfect sense to them:

> [john 3:16 - NIV]
>  16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.

But the below does NOT:

> [!Bible] [john 3:16 - NIV](https://bolls.life/NIV/43/3/)
>  16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.

They don't understand why the [!Bible] tag is there, and urls are useless to them because they do not have internet access of course.  So I have to strip these out manually, or else send them stuff that confuses them and looks like strings of garbage to them.

An option to leave out the [!Bible] tag and url would be of great use to me.

Again, thank you.  This tool has really improved my ability to work on sermons and bible studies easily, intuitively, and quickly.  I really appreciate it.

**Comment by tim-hub** [comment]
> I would like to add my voice to this request.
> 
> obsidian-bible-reference is an absolutely WONDERFUL tool, thank you for it.
> 
> But it would be even more useful to me if there were an option to eliminate the [!Bible] tag AND the url.  I work in prison ministry and I often transfer bible study notes from obsidian to Securus.  Securus is, essentially, an email system for the prisoners in the Texas prison system.  It is very simple, of course, and only allows text.  No fancy formatting, and no mark down.  Of course, one of the beautiful things about markdown is that the vast majority of it makes perfect sense as plain text.  When I copy bible study notes from obsidian into Securus for an inmate, this makes perfect sense to them:
> 
> \> john 3:16 - NIV
> \>  16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> But the below does NOT:
> 
> \> [!Bible] [john 3:16 - NIV](https://bolls.life/NIV/43/3/)
> \>  16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> They don't understand why the [!Bible] tag is there, and urls are useless to them because they do not have internet access of course.  So I have to strip these out manually, or else send them stuff that confuses them and looks like strings of garbage to them.
> 
> An option to leave out the [!Bible] tag and url would be of great use to me.
> 
> Again, thank you.  This tool has really improved my ability to work on sermons and bible studies easily, intuitively, and quickly.  I really appreciate it.
> 

Thanks for your sharing.

Let me find time to add this setting.

**Comment by tim-hub** [comment]
> I would like to add my voice to this request.
> 
> obsidian-bible-reference is an absolutely WONDERFUL tool, thank you for it.
> 
> But it would be even more useful to me if there were an option to eliminate the [!Bible] tag AND the url. I work in prison ministry and I often transfer bible study notes from obsidian to Securus. Securus is, essentially, an email system for the prisoners in the Texas prison system. It is very simple, of course, and only allows text. No fancy formatting, and no mark down. Of course, one of the beautiful things about markdown is that the vast majority of it makes perfect sense as plain text. When I copy bible study notes from obsidian into Securus for an inmate, this makes perfect sense to them:
> 
> > john 3:16 - NIV > 16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> But the below does NOT:
> 
> > [!Bible] [john 3:16 - NIV](https://bolls.life/NIV/43/3/) > 16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> They don't understand why the [!Bible] tag is there, and urls are useless to them because they do not have internet access of course. So I have to strip these out manually, or else send them stuff that confuses them and looks like strings of garbage to them.
> 
> An option to leave out the [!Bible] tag and url would be of great use to me.
> 
> Again, thank you. This tool has really improved my ability to work on sermons and bible studies easily, intuitively, and quickly. I really appreciate it.

@Kilarin 

Would you mind trying the new version 2.4.0

With the new settings, it will be able to get a minimal version output now.

https://antioch.tech/obsidain-bible-reference-plugin-2-4-0-changelog/


I will close this for now, but feel free to comment more questions or re-open this.

**Comment by Kilarin** [comment]
Sorry for the slow response.  Life got very busy for me for a while. :)
Thank you so much!  This is awesome!
Is there a way we could still get the Bible book and chapter, when selecting "Hide (clean and simple)"?

I get:
> 
>  16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.

It would be great to get:
>  John 3:16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.

or even:
> John 3:16
> 16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.

Again, thank you so very much.  You put a lot of work into this, and it helps so many people!

**Comment by tim-hub** [comment]
> Sorry for the slow response. Life got very busy for me for a while. :) Thank you so much! This is awesome! Is there a way we could still get the Bible book and chapter, when selecting "Hide (clean and simple)"? Just without the url?
> 
> I get:
> 
> > 16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> It would be great to get:
> 
> > John 3:16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> or even:
> 
> > John 3:16
> > 16. “For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.
> 
> Again, thank you so very much. You put a lot of work into this, and it helps so many people!

Thanks for the feedback, would put this in consider for the formatting in the future.
