### ISSUE TITLE
Allow the Callout Link to be to the actual bible verse/chapter rather than the API call

### ISSUE THREAD

**Issue by Bill77** [tim-hub/obsidian-bible-reference#84]
**Is your feature request related to a problem? Please describe.**

I was expecting the scripture reference would link to the Bible scripture rather than the JSON request made. Often, with scripture references, it would be nice to be able to read the scriptures around it. So if the link would lead me back to the chapter/verse in an online bible that would be really helpful.

> Potentially an even "cooler" option is a tooltip preview of the verse and the chapter around it (since we already get that from the Bolls Life API).

**Describe the solution you'd like**

I would like the link to the scripture to take me to an online bible where the book and chapter (and potentially verse) is selected.
Looking at the link info, specifically for the Bolls Life API, we can navigate directly to the chapter in it's online view by changing the link information from

`[!Bible] [john 10:10 - ESV](https://bolls.life/get-text/ESV/43/10/)`

to the following and removing the `get-text` route.

`[!Bible] [john 10:10 - ESV](https://bolls.life/ESV/43/10/)`

**Describe alternatives you've considered**

As briefly mentioned, potentially instead of a link, we could also display a tooltip with the chapter (potentially with the verse(s) in bold).

**Additional context**

<img width="247" alt="image" src="https://user-images.githubusercontent.com/7854207/222996052-622bef8f-83c6-4b49-babc-79fbbc99e86f.png">

**Comment by Bill77** [comment]
I know for the Bible API we'd need another solution. Perhaps we can provide options? [Bible Gateway](https://www.biblegateway.com)?

I was also considering building one to esv.org since they have an API as well, and I already own the study bible with their online account, so that'd be specifically handy for me. :)

**Comment by Bill77** [comment]
Hi @tim-hub, not sure if you saw the notification, but I made a PR for this change. Be happy to continue contributing if that's helpful. 😄

**Comment by tim-hub** [comment]
> Hi @tim-hub, not sure if you saw the notification, but I made a PR for this change. Be happy to continue contributing if that's helpful. 😄

HI @Bill77 Do you mean this PR?

This change is in PR #85

**Comment by Bill77** [comment]
Hi @tim-hub, 

Yes, I think this issue is resolved (I believe). :)

**Comment by Bill77** [comment]
Sorry, didn't realize I could close the issue. :)
