### ISSUE TITLE
Allow verse to be a footnote

### ISSUE THREAD

**Issue by Jfreyman7** [tim-hub/obsidian-bible-reference#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Enable the verse to be appended to the footnote rather than inline with the verse. Obsidian has built-in footnote syntax.

**Describe alternatives you've considered**

**Additional context**

**Comment by tim-hub** [comment]
Hi @Jfreyman7 


Can you give more description of your requirements? Any screenshot or markdown example?

**Comment by RandomUserWithInternet** [comment]
This is a cool idea, but I don't think it will work with the current way that verses are formatted in the embed style. If you try and maintain the embed style, it will just leave the footnote section. Without the `>`s it will work just fine, but it won't look pretty. 
I'd imagine that when you implement this, there would be a new command for it. Maybe `-^Book1:1`? 
![image](https://github.com/tim-hub/obsidian-bible-reference/assets/88126013/e98ec8f6-19da-4098-ba89-fb9c6d831150)
