### ISSUE TITLE
Request whole chapter

### ISSUE THREAD

**Issue by android272** [tim-hub/obsidian-bible-reference#88]
**Is your feature request related to a problem? Please describe.**
There are times when I would like to print out the entire chapter or the rest of the chapter. The problem is that I don't necessarily know how many verses are in this chapter. 

**Describe the solution you'd like**
It would be nice if passing 0 would select the whole chapter. So you could for example:

--Matthew17:0 - prints out full chapter (27 verses)
--Matthew17:17-0 - prints verses 17 through the end of the chapter (verse 17 - 17)

**Describe alternatives you've considered**

--Matthew17:full - prints out full chapter (27 verses)
--Matthew17:17-full - prints verses 17 through the end of the chapter (verse 17 - 17)

**Comment by tim-hub** [comment]
@android272 this seems like a duplication of another issue #86

**Comment by android272** [comment]
Yep your right. Sorry about that.

**Comment by tim-hub** [comment]
> Yep your right. Sorry about that.

Thanks for
