### ISSUE TITLE
Suggest books

### ISSUE THREAD

**Issue by android272** [tim-hub/obsidian-bible-reference#89]
**Is your feature request related to a problem? Please describe.**
Some of the books of the Bible are hard to spell. 

**Describe the solution you'd like**
It would be nice if while typing the name of the book if the verse selector that shows the whole verse would pop up with just the name of the book.

![Screenshot_20230319-101541](https://user-images.githubusercontent.com/5912527/226182593-f1746a51-9aef-4140-a663-a4c7c8861bbb.png)

![Screenshot_20230319-102627](https://user-images.githubusercontent.com/5912527/226182685-8c8baba0-561c-4a33-aeae-2c782bbb9458.png)

Tipping Matt would show Matthew, and tapping it would then insert the whole word. Typing King would show 1 Kings and 2 Kings; typing Cor would show 1 Corinthians and 2 Corinthians.

**Comment by hi-reeve** [comment]
would love to see this also. will be good if there is book suggestion while we are typing.

**Comment by tim-hub** [comment]
> would love to see this also. will be good if there is book suggestion while we are typing.

This will be a big change, it will change the behavior of the app, need to think about it thoroughly.

**Comment by RamchandraWarang9822** [comment]
Would love to see this, Support to implement this as book suggestion would improve the speed of the user to quote the correct book and bible verse faster
