### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by SamH765** [tim-hub/obsidian-bible-reference#91]
I love the plugin and use it almost daily. Yesterday, I couldn't get it to work at all, and am still having the same issue today. Any ideas of what I can try?

Thanks in advance for any help :)

**Comment by tim-hub** [comment]
Thanks for the issue update. Will have a look.

**Comment by SamH765** [comment]
Seems like it could be a compatibility issue with the emoji shortcodes plugin. I disabled that plugin and the reference plugin worked again.

**Comment by tim-hub** [comment]
thanks for the update, will mark this as closed for now, I am not sure there is a perfect way to solve the conflicts without changing the bahavior. 😢
