### ISSUE TITLE
Add the option to format the text in Markdown rather than HTML

### ISSUE THREAD

**Issue by JTravisWatson** [tim-hub/obsidian-bible-reference#92]
The option to have the text formatted using markdown would help the uniformity across multiple notes. This also helps the text render properly when opened in other markdown editors. 

At the moment, I wait for the plug-in to populate the text, and then I reformat manually. For example I change `<sup> **16** </sup>` to `**$^{16}$**`

This is a bigger ask, but the ability to customize the callout that is created would also be appreciated. I have a custom “Verse” callout I use, and at the moment I reformat the output to conform.

**Comment by JTravisWatson** [comment]
I have modified some of the JS to produce my desired output.
Here is what I modified the Superscript Bold case to output: 
``` 
       case "**^1**" /* SuperScriptBold */:
        verseNumberFormatted += "**$^{" + verseNumber + "}$** ";
        return verseNumberFormatted; `
```

Sorry if this is not the proper channel for this type of feedback, but I got it to work for me.  I know it won’t survive an update, though. 

I also changed the `>[!Bible]` line to output my `>[!verse]` callout.

**Comment by tim-hub** [comment]
I need to do investigation on it to verify whether it makes the same.
And how to offer different output options at the same time.

**Comment by SamejSpenser** [comment]
> At the moment, I wait for the plug-in to populate the text, and then I reformat manually. For example I change `<sup> **16** </sup>` to `**$^{16}$**`

I tend to manually replace with superscript number characters (I created keyboard shortcuts with [espanso](https://github.com/espanso/espanso): `;1`, `;2`… `;0`), that way:

```
> [!bible] John 3:16 • AMP
> ¹⁰ “For God so _[greatly]_ loved _and_ dearly prized the world, that He _[even]_ gave His _[One and]_ only begotten Son, so that whoever believes _and_ trusts in Him _[as Savior]_ shall not perish, but have eternal life.
```
